var sentence_concordance = [{'postposition':'ey','function':'agt','sentences':[{'name':'-에 (-ey)','sentence':'셰익스피어에 대한 전기는 구구하다.','pos_sentence':'셰익스피어/NNP 에/JKB 대하__02/VV ᆫ/ETM 전기__12/NNG 는/JX 구구/XR 하/XSA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'Merton에 의해 제기되었다.','pos_sentence':'Merton/SL 에/JKB 의하/VV 아/EC 제기__06/NNG 되/XSV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 우리는 늘 가난에 쫓기고 있었다.','pos_sentence':'그러나/MAJ 우리/NP 는/JX 늘/MAG 가난__01/NNG 에/JKB 쫓기/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'1802 년, 돌턴에 의하여 제창되었다.','pos_sentence':'1802/SN 년__02/NNB ,/SP 돌턴/NNP 에/JKB 의하/VV 아/EC 제창__04/NNG 되/XSV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그리고 만돌이가 경찰에 맞은 것일까.','pos_sentence':'그리고/MAJ 만돌이/NNP 가/JKS 경찰__04/NNG 에/JKB 맞__03/VV 은/ETM 것/NNB 이/VCP ᆯ까/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그만큼 구설수에 시달리기도 했다.','pos_sentence':'그만큼/MAG 구설수/NNG 에/JKB 시달리/VV 기/ETN 도/JX 하/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'디드로와 달랑베르에 의해 1751년부터','pos_sentence':'디드로/NNP 와/JC 달랑베르/NNP 에/JKB 의하/VV 아/EC 1751/SN 년__02/NNB 부터/JX'},
{'name':'-에 (-ey)','sentence':'주로 하층계급에 의해 발생한다.','pos_sentence':'주로/MAG 하층/NNG 계급__02/NNG 에/JKB 의하/VV 아/EC 발생/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'컴퓨터 프로그램이 저작권에 의해 보호되는 범위','pos_sentence':'컴퓨터/NNG 프로그램/NNG 이/JKS 저작__03/NNG 권/XSN 에/JKB 의하/VV 아/EC 보호__01/NNG 되/XSV 는/ETM 범위/NNG'},
{'name':'-에 (-ey)','sentence':'무엇이 눈에 띄었을까?','pos_sentence':'무엇/NP 이/JKS 눈__01/NNG 에/JKB 띄/VV 었/EP 을까/EF ?/SF'},
{'name':'-에 (-ey)','sentence':'부산 대구 인천 차량도 눈에 띄었다.','pos_sentence':'부산/NNP 대구/NNP 인천/NNP 차량__01/NNG 도/JX 눈__01/NNG 에/JKB 띄__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그래서 논리의 비약도 눈에 뜨인다.','pos_sentence':'그래서/MAJ 논리/NNG 의/JKG 비약/NNG 도/JX 눈__01/NNG 에/JKB 뜨이__02/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'약국이 그의 시선에 걸렸다.','pos_sentence':'약국__02/NNG 이/JKS 그/NP 의/JKG 시선__03/NNG 에/JKB 걸리__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아무도 눈에 띄지 않았다.','pos_sentence':'아무/NP 도/JX 눈__01/NNG 에/JKB 띄__01/VV 지/EC 않/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 유일이는 그것에 치이고 말았다.','pos_sentence':'그러나/MAJ 유일이/NNP 는/JX 그것/NP 에/JKB 치이__02/VV 고/EC 말/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그래서 마을도 별로 눈에 띄지 않았다.','pos_sentence':'그래서/MAJ 마을__01/NNG 도/JX 별로/MAG 눈__01/NNG 에/JKB 띄__01/VV 지/EC 않/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'난 공연히 엉뚱한 생각에 사로잡혔다.','pos_sentence':'나/NP ᆫ/JX 공연히__02/MAG 엉뚱/XR 하/XSA ᆫ/ETM 생각__01/NNG 에/JKB 사로잡히/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'비로소 상처가 자세히 눈에 들어왔다.','pos_sentence':'비로소/MAG 상처__02/NNG 가/JKS 자세히/MAG 눈__01/NNG 에/JKB 들어오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'형의 목소리가 기타 소리에 묻혔다.','pos_sentence':'형__01/NNG 의/JKG 목소리/NNG 가/JKS 기타__02/NNG 소리__01/NNG 에/JKB 묻히__02/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'바깥의 소음에 묻힌다.','pos_sentence':'바깥/NNG 의/JKG 소음__06/NNG 에/JKB 묻히__02/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'양혜왕은 맹자의 논리에 걸려들었습니다.','pos_sentence':'양혜왕/NNP 은/JX 맹자/NNP 의/JKG 논리/NNG 에/JKB 걸려들/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'선물가게의 모습이 눈에 띄었다.','pos_sentence':'선물__03/NNG 가게/NNG 의/JKG 모습__01/NNG 이/JKS 눈__01/NNG 에/JKB 띄__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'거짓말처럼 아무도 눈에 띄지 않았다.','pos_sentence':'거짓말/NNG 처럼/JKB 아무/NP 도/JX 눈__01/NNG 에/JKB 띄__01/VV 지/EC 않/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'얼굴이 눈에 띄게 핼쑥했다.','pos_sentence':'얼굴/NNG 이/JKS 눈__01/NNG 에/JKB 띄__01/VV 게/EC 핼쑥/XR 하/XSA 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'남자의 뒷모습이 눈에 익었다.','pos_sentence':'남자__02/NNG 의/JKG 뒷모습/NNG 이/JKS 눈__01/NNG 에/JKB 익/VA 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'자연에 맡기면 된다.','pos_sentence':'자연__01/NNG 에/JKB 맡기/VV 면/EC 되/VX ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'국제 항공로 항공기에 의한 국제 간의 교통 노선.','pos_sentence':'국제/XR 항공로/NNG 항공기/NNG 에/JKB 의하/VV ᆫ/ETM 국제/XR 간__10/NNB 의/JKG 교통__01/NNG 노선/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'연습실은 괴괴한 적막에 파묻혔다.','pos_sentence':'연습실/NNG 은/JX 괴괴/XR 하/XSA ᆫ/ETM 적막__01/NNG 에/JKB 파묻히/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'간혹 눈에 띈다.','pos_sentence':'간혹/MAG 눈__01/NNG 에/JKB 띄__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'철야 또는 야간의 계속적 신문에 의한 자백','pos_sentence':'철야/NNG 또는/MAG 야간/NNG 의/JKG 계속__04/NNG 적/XSN 신문__07/NNG 에/JKB 의하/VV ᆫ/ETM 자백__01/NNG'},
{'name':'-에 (-ey)','sentence':'국민 저축 조합법에 의한 강제적 저금이다.','pos_sentence':'국민/NNG 저축/NNG 조합법/NNG 에/JKB 의하/VV ᆫ/ETM 강제__01/NNG 적/XSN 저금/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'눈에 보이는 놀이터만이 아니다.','pos_sentence':'눈__01/NNG 에/JKB 보이__01/VV 는/ETM 놀이터/NNG 만/JX 이/JKC 아니/VCN 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'눈에 보이는 이미지','pos_sentence':'눈__01/NNG 에/JKB 보이__01/VV 는/ETM 이미지/NNG'},
{'name':'-에 (-ey)','sentence':'경쟁은 눈에 띄게 계속되었다.','pos_sentence':'경쟁/NNG 은/JX 눈__01/NNG 에/JKB 띄__01/VV 게/EC 계속__04/NNG 되/XSV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'눈에 띄는 제품들','pos_sentence':'눈__01/NNG 에/JKB 띄__01/VV 는/ETM 제품__02/NNG 들/XSN'},
{'name':'-에 (-ey)','sentence':'선임권, 접견교통권의 침해에 의한 자백','pos_sentence':'선임__03/NNG 권/XSN ,/SP 접견/NNG 교통__01/NNG 권/XSN 의/JKG 침해/NNG 에/JKB 의하/VV ᆫ/ETM 자백__01/NNG'},
{'name':'-에 (-ey)','sentence':'분산되고 다른 것에 의해 대체된다.','pos_sentence':'분산__02/NNG 되/XSV 고/EC 다른/MM 것/NNB 에/JKB 의하/VV 아/EC 대체__03/NNG 되/XSV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그것도 나를 배신한 사람에 의해.','pos_sentence':'그것/NP 도/JX 나/NP 를/JKO 배신__02/NNG 하/XSV ᆫ/ETM 사람/NNG 에/JKB 의하/VV 아/EF ./SF'},
{'name':'-에 (-ey)','sentence':'5학년 광택이가 눈에 띄었다.','pos_sentence':'5/SN 학년/NNG 광택이/NNP 가/JKS 눈__01/NNG 에/JKB 띄__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'마을은 산그늘에 묻히고 있었다.','pos_sentence':'마을__01/NNG 은/JX 산그늘/NNG 에/JKB 묻히__02/VV 고/EC 있/VX 었/EP 다/EF ./SF'}]}
,{'postposition':'ey','function':'crt','sentences':[{'name':'-에 (-ey)','sentence':'이것은 일반 논리에 어긋난 표현이다.','pos_sentence':'이것/NP 은/JX 일반__02/NNG 논리/NNG 에/JKB 어긋나/VV ᆫ/ETM 표현/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'오랜만에 교실안은 고요를 되찾았습니다.','pos_sentence':'오랜만/NNG 에/JKB 교실/NNG 안__01/NNG 은/JX 고요__01/NNG 를/JKO 되찾/VV 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'한참 뒤에 의사가 왔다.','pos_sentence':'한참/NNG 뒤__01/NNG 에/JKB 의사__12/NNG 가/JKS 오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그럼 두 시경에 역 앞에서 만납시다.','pos_sentence':'그럼/MAJ 두/MM 시/NNB 경/XSN 에/JKB 역__14/NNG 앞/NNG 에서/JKB 만나/VV ᄇ시다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'일주일에 몇 시간이나 노동을 하는지.','pos_sentence':'일주일/NNG 에/JKB 몇/MM 시간__04/NNG 이나/JX 노동__03/NNG 을/JKO 하/VV 는지/EF ./SF'},
{'name':'-에 (-ey)','sentence':'J씨가 바로 이런 경우에 속한다.','pos_sentence':'J/SL 씨/NNB 가/JKS 바로/MAG 이런/MM 경우__03/NNG 에/JKB 속하__02/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'가부간에 곧 연락을 드리겠습니다.','pos_sentence':'가부간/MAG 에/JKB 곧/MAG 연락__02/NNG 을/JKO 드리__01/VV 겠/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'하지만 한술 밥에 배부르랴.','pos_sentence':'하지만/MAJ 한술/NNG 밥__01/NNG 에/JKB 배부르/VA 랴/EF ./SF'},
{'name':'-에 (-ey)','sentence':'울산은 승점 61점에 그쳤다.','pos_sentence':'울산/NNP 은/JX 승점/NNG 61/SN 점__10/NNB 에/JKB 그치/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'특히 요추 4번에 주의를 기울여야 한다.','pos_sentence':'특히/MAG 요추__02/NNG 4/SN 번/NNB 에/JKB 주의__07/NNG 를/JKO 기울이/VV 어야/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'2주 후에 에티오피아로 떠나요.','pos_sentence':'2/SN 주__26/NNB 후__08/NNG 에/JKB 에티오피아/NNP 로/JKB 떠나/VV 요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'7년 만에 만났어요.','pos_sentence':'7/SN 년__02/NNB 만__01/NNB 에/JKB 만나/VV 았/EP 어요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리는 현재 문화적 환절기에 와 있다.','pos_sentence':'우리/NP 는/JX 현재/MAG 문화__01/NNG 적/XSN 환절기__01/NNG 에/JKB 오/VV 아/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'식전에 무우밭을 맸다.','pos_sentence':'식전__03/NNG 에/JKB 무우__01/NNG 밭/NNG 을/JKO 매__02/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'여기가 마음에 드시지 않던가요?','pos_sentence':'여기/NP 가/JKS 마음__01/NNG 에/JKB 들__01/VV 시/EP 지/EC 않/VX 던가요/EF ?/SF'},
{'name':'-에 (-ey)','sentence':'우리는 기술 문명의 아주 초기 단계에 있다.','pos_sentence':'우리/NP 는/JX 기술__01/NNG 문명/NNG 의/JKG 아주/MAG 초기/NNG 단계__03/NNG 에/JKB 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'여전히 마음에 걸리는 모양이었다.','pos_sentence':'여전히/MAG 마음__01/NNG 에/JKB 걸리__01/VV 는/ETM 모양__02/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'지그재그 폭을 1~5에 놓는다.','pos_sentence':'지그재그/NNG 폭__06/NNG 을/JKO 1/SN ~/SO 5/SN 에/JKB 놓__01/VV 는다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그날 밤 이후에 생긴 습관이다.','pos_sentence':'그날/NNG 밤__01/NNG 이후__02/NNG 에/JKB 생기/VV ᆫ/ETM 습관/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그 단순함이 네 마음에 든다.','pos_sentence':'그/MM 단순__02/NNG 하/XSA ᄆ/ETN 이/JKS 너/NP 의/JKG 마음__01/NNG 에/JKB 들__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'사전에 자세히 물어보았어야 했다.','pos_sentence':'사전__13/NNG 에/JKB 자세히/MAG 묻__03/VV 어/EC 보/VX 았/EP 어야/EC 하/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'오랜만에 먹어보는 것이었다.','pos_sentence':'오랜만/NNG 에/JKB 먹__02/VV 어/EC 보/VX 는/ETM 것/NNB 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'대중사회의 인간 심리는 유행에 약하다.','pos_sentence':'대중__02/NNG 사회__07/NNG 의/JKG 인간__01/NNG 심리__01/NNG 는/JX 유행__02/NNG 에/JKB 약하/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이틀 뒤에 그녀는 숨을 거두었다.','pos_sentence':'이틀__01/NNG 뒤__01/NNG 에/JKB 그녀/NP 는/JX 숨__01/NNG 을/JKO 거두/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'간밤에 확인한 방문을 두드렸다.','pos_sentence':'간밤/NNG 에/JKB 확인__02/NNG 하/XSV ᆫ/ETM 방문__02/NNG 을/JKO 두드리/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'영국인 다음으로 5위에 떨어지고 있다.','pos_sentence':'영국인/NNG 다음__01/NNG 으로/JKB 5/SN 위/NNB 에/JKB 떨어지/VV 고/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러고는 기자시험에 합격했다.','pos_sentence':'그러/VV 고는/EC 기자__05/NNG 시험__03/NNG 에/JKB 합격/NNG 하/XSV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'기행문의 대부분도 후자에 속한다.','pos_sentence':'기행문/NNG 의/JKG 대부분/NNG 도/JX 후자/NNG 에/JKB 속하__02/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'올 봄에 받은 꽃씨요.','pos_sentence':'올/MM 봄/NNG 에/JKB 받__01/VV 은/ETM 꽃씨/NNG 이/VCP 오/EF ./SF'},
{'name':'-에 (-ey)','sentence':'묘소에서는 하루 전에 광중을 판다.','pos_sentence':'묘소__03/NNG 에서/JKB 는/JX 하루__01/NNG 전__08/NNG 에/JKB 광중/NNG 을/JKO 파__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'취미론은 주관과 객관에 양다리를 걸친다.','pos_sentence':'취미__04/NNG 론/XSN 은/JX 주관__02/NNG 과/JC 객관__03/NNG 에/JKB 양다리/NNG 를/JKO 걸치/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그리고 1976 여름에 둘째 아들을 장가 보냈다.','pos_sentence':'그리고/MAJ 1976/SN 여름__01/NNG 에/JKB 둘째/NR 아들/NNG 을/JKO 장가__01/NNG 보내/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'간밤에 또 눈이 내린 것이다.','pos_sentence':'간밤/NNG 에/JKB 또/MAJ 눈__04/NNG 이/JKS 내리/VV ᆫ/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'문법에 맞는가?','pos_sentence':'문법__01/NNG 에/JKB 맞__01/VV 는가/EF ?/SF'},
{'name':'-에 (-ey)','sentence':'내 차는 새벽에 저절로 섰다.','pos_sentence':'나/NP 의/JKG 차__06/NNG 는/JX 새벽__01/NNG 에/JKB 저절로/MAG 서/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'원혁이는 팔만 원에 오토바이를 샀다.','pos_sentence':'원혁이/NNP 는/JX 팔만/NR 원__01/NNB 에/JKB 오토바이/NNG 를/JKO 사/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'난 한달 전에 아기를 낳았어요.','pos_sentence':'나/NP ᆫ/JX 한/MM 달/NNB 전__08/NNG 에/JKB 아기__01/NNG 를/JKO 낳__01/VV 았/EP 어요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'0에 위치하면 천이 움직이지 않는다.','pos_sentence':'0/SN 에/JKB 위치__01/NNG 하/XSV 면/EC 천__01/NNG 이/JKS 움직이/VV 지/EC 않/VX 는다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'결혼식 첫날밤에 등잔불을 입으로 끄지 않는다','pos_sentence':'결혼식/NNG 첫날밤/NNG 에/JKB 등잔불/NNG 을/JKO 입/NNG 으로/JKB 끄__01/VV 지/EC 않/VX 는다/EC'},
{'name':'-에 (-ey)','sentence':'황제펭귄은 한겨울에 알을 낳는대요.','pos_sentence':'황제펭귄/NNG 은/JX 한/XPN 겨울/NNG 에/JKB 알/NNG 을/JKO 낳__01/VV 는대요/EF ./SF'},]}
,{'postposition':'ey','function':'eff','sentences':[{'name':'-에 (-ey)','sentence':'그 말에 최재걸이 짐짓 경색을 지으며,','pos_sentence':'그/MM 말__01/NNG 에/JKB 최재걸/NNP 이/JKS 짐짓/MAG 경색__01/NNG 을/JKO 짓__01/VV 으며/EC ,/SP'},
{'name':'-에 (-ey)','sentence':'그 천진한 표정에 마음이 풀렸다.','pos_sentence':'그/MM 천진__03/NNG 하/XSA ᆫ/ETM 표정__03/NNG 에/JKB 마음__01/NNG 이/JKS 풀리/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그는 설움에 말문이 막히곤 하였다.','pos_sentence':'그/NP 는/JX 설움/NNG 에/JKB 말문__01/NNG 이/JKS 막히/VV 곤/EC 하/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이 말에 나도 생각이 났다.','pos_sentence':'이/MM 말__01/NNG 에/JKB 나/NP 도/JX 생각__01/NNG 이/JKS 나/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'영어 실력에 대한 자신감 때문이다.','pos_sentence':'영어/NNP 실력__02/NNG 에/JKB 대하__02/VV ᆫ/ETM 자신감/NNG 때문/NNB 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'박창길의 말에 이재필이 장단을 먹였다.','pos_sentence':'박창길/NNP 의/JKG 말__01/NNG 에/JKB 이재필/NNP 이/JKS 장단__01/NNG 을/JKO 먹이/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'온몸이 땀에 흠뻑 젖어 있었다.','pos_sentence':'온몸/NNG 이/JKS 땀__01/NNG 에/JKB 흠뻑/MAG 젖__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이 말에 레빈은 갑자기 열이 났다.','pos_sentence':'이/MM 말__01/NNG 에/JKB 레빈/NNP 은/JX 갑자기/MAG 열__07/NNG 이/JKS 나/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그 음성에 첫째 어머니는 왈칵 내달았다.','pos_sentence':'그/MM 음성__02/NNG 에/JKB 첫째/NR 어머니/NNG 는/JX 왈칵/MAG 내닫/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그리고 그 등쌀에 시름하는 층은 같다.','pos_sentence':'그리고/MAJ 그/MM 등쌀/NNG 에/JKB 시름/NNG 하/XSV 는/ETM 층__02/NNG 은/JX 같/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'덕분에 잘 지냈시다.','pos_sentence':'덕분/NNG 에/JKB 잘/MAG 지내/VV 었/EP 시다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그 말에 아버지는 새삼 그림을 바라본다.','pos_sentence':'그/MM 말__01/NNG 에/JKB 아버지/NNG 는/JX 새삼/MAG 그림__01/NNG 을/JKO 바라보/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'오히려 그 때문에 부패가 더 생긴다.','pos_sentence':'오히려/MAG 그/MM 때문/NNB 에/JKB 부패__04/NNG 가/JKS 더/MAG 생기/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그 기세에 LG타자가 밀렸다.','pos_sentence':'그/MM 기세__01/NNG 에/JKB LG/SL 타자__03/NNG 가/JKS 밀리__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'내 말에 영순이는 눈을 흘겼다.','pos_sentence':'나/NP 의/JKG 말__01/NNG 에/JKB 영순이/NNP 는/JX 눈__01/NNG 을/JKO 흘기/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'덕분에 금전적 출혈이 심하다.','pos_sentence':'덕분/NNG 에/JKB 금전__05/NNG 적/XSN 출혈/NNG 이/JKS 심하/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그것 때문에 가정부와 다투기까지 했다.','pos_sentence':'그것/NP 때문/NNB 에/JKB 가정부__01/NNG 와/JKB 다투/VV 기/ETN 까지/JX 하/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이 바람에 잠이 깨었습니다.','pos_sentence':'이/MM 바람__01/NNB 에/JKB 잠__01/NNG 이/JKS 깨__01/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'매일 돈 때문에 엄마와 아빠가 싸우세요.','pos_sentence':'매일/MAG 돈__01/NNG 때문/NNB 에/JKB 엄마/NNG 와/JKB 아빠/NNG 가/JKS 싸우/VV 시/EP 어요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이것 때문에 이혼율이 높아졌다.','pos_sentence':'이것/NP 때문/NNB 에/JKB 이혼__03/NNG 율/XSN 이/JKS 높/VA 아/EC 지/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그는 이런 생각에 얼굴이 화끈 달았다.','pos_sentence':'그/NP 는/JX 이런/MM 생각__01/NNG 에/JKB 얼굴/NNG 이/JKS 화끈/MAG 달__01/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'지현의 말에 정희는 깜빡 제정신을 돌린다.','pos_sentence':'지현/NNP 의/JKG 말__01/NNG 에/JKB 정희/NNP 는/JX 깜빡/MAG 제정신/NNG 을/JKO 돌리__04/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'결혼은 사회적 지위 때문에 한다.','pos_sentence':'결혼/NNG 은/JX 사회__07/NNG 적/XSN 지위__04/NNG 때문/NNB 에/JKB 하/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'석양빛에 앞벌은 비단결 같다.','pos_sentence':'석양빛/NNG 에/JKB 앞벌/NNG 은/JX 비단결/NNG 같/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'유간사는 노크 소리에 고개를 쳐들었다.','pos_sentence':'유/NNP 간사__06/NNG 는/JX 노크/NNG 소리__01/NNG 에/JKB 고개__01/NNG 를/JKO 쳐들/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그 통에 구두 한 짝이 벗겨졌어요.','pos_sentence':'그/MM 통__06/NNB 에/JKB 구두__01/NNG 한/MM 짝__01/NNG 이/JKS 벗겨지/VV 었/EP 어요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'흐느낌 때문에 온몸이 떨렸다.','pos_sentence':'흐느낌/NNG 때문/NNB 에/JKB 온몸/NNG 이/JKS 떨리__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'뜻밖의 말에 옥점이는 호호 웃었다.','pos_sentence':'뜻밖/NNG 의/JKG 말__01/NNG 에/JKB 옥점이/NNP 는/JX 호호__02/MAG 웃/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'나는 오줌 때문에 눈을 떴다.','pos_sentence':'나/NP 는/JX 오줌/NNG 때문/NNB 에/JKB 눈__01/NNG 을/JKO 뜨__05/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아침햇살과 새소리에 눈을 떴습니다.','pos_sentence':'아침/NNG 햇살/NNG 과/JC 새소리/NNG 에/JKB 눈__01/NNG 을/JKO 뜨__05/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'요즘 우리는 돈 때문에 무척 시달립니다.','pos_sentence':'요즘/NNG 우리/NP 는/JX 돈__01/NNG 때문/NNB 에/JKB 무척/MAG 시달리/VV ᄇ니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'억울한 생각에 입술을 깨물었습니다.','pos_sentence':'억울/XR 하/XSA ᆫ/ETM 생각__01/NNG 에/JKB 입술/NNG 을/JKO 깨물/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'두꺼비의 말에 태봉이는 껄껄 웃었다.','pos_sentence':'두꺼비/NNG 의/JKG 말__01/NNG 에/JKB 태봉이/NNP 는/JX 껄껄/MAG 웃/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'해방 덕분에 풀려난 거죠.','pos_sentence':'해방__05/NNG 덕분/NNG 에/JKB 풀려나/VV ᆫ/ETM 거/NNB 이/VCP 죠/EF ./SF'},
{'name':'-에 (-ey)','sentence':'스잔의 농담에 미혜가 웃었다.','pos_sentence':'스잔/NNP 의/JKG 농담__01/NNG 에/JKB 미혜/NNP 가/JKS 웃/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그녀가 그 소리에 눈을 반짝 떴다.','pos_sentence':'그녀/NP 가/JKS 그/MM 소리__01/NNG 에/JKB 눈__01/NNG 을/JKO 반짝__02/MAG 뜨__05/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'살의 때문에 손이 떨렸다.','pos_sentence':'살의/NNG 때문/NNB 에/JKB 손__01/NNG 이/JKS 떨리__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'바람에 흔들리는 나뭇잎.','pos_sentence':'바람__01/NNG 에/JKB 흔들리/VV 는/ETM 나뭇잎/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'경지의 말에 점원 아가씨가 생긋 웃었다.','pos_sentence':'경지/NNP 의/JKG 말__01/NNG 에/JKB 점원__01/NNG 아가씨/NNG 가/JKS 생긋/MAG 웃/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'품이는 은영이 생각에 슬펐습니다.','pos_sentence':'품이/NNP 는/JX 은영이/NNP 생각__01/NNG 에/JKB 슬프/VA 었/EP 습니다/EF ./SF'}]}
,{'postposition':'ey','function':'fns','sentences':[{'name':'-에 (-ey)','sentence':'그녀는 씁쓰름한 기분에 빠진다.','pos_sentence':'그녀/NP 는/JX 씁쓰름/XR 하/XSA ᆫ/ETM 기분__01/NNG 에/JKB 빠지__02/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아내는 남편의 소유물에 지나지 않았다.','pos_sentence':'아내__01/NNG 는/JX 남편__01/NNG 의/JKG 소유물/NNG 에/JKB 지나/VV 지/EC 않/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리는 번역문화의 후진국에 머물러 있다.','pos_sentence':'우리/NP 는/JX 번역/NNG 문화__01/NNG 의/JKG 후진국/NNG 에/JKB 머무르/VV 어/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그래서 도의 본래 모습에 가깝다.','pos_sentence':'그래서/MAJ 도__10/NNG 의/JKG 본래/NNG 모습__01/NNG 에/JKB 가깝/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리 주력업종이 성숙기에 있다.’','pos_sentence':'우리/NP 주력__01/NNG 업종__01/NNG 이/JKS 성숙기/NNG 에/JKB 있/VV 다/EF ./SF ’/SS'},
{'name':'-에 (-ey)','sentence':'바그다드는 슬픔에 젖어 있다.','pos_sentence':'바그다드/NNP 는/JX 슬픔/NNG 에/JKB 젖__01/VV 어/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'청와대는 이미 내핍 생활에 들어간 것이다.','pos_sentence':'청와대/NNP 는/JX 이미/MAG 내핍/NNG 생활/NNG 에/JKB 들어가__01/VV ᆫ/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'정말 나는 텔레비전 중독에 걸린 모양이다.','pos_sentence':'정말/MAG 나/NP 는/JX 텔레비전/NNG 중독__01/NNG 에/JKB 걸리__01/VV ᆫ/ETM 모양__02/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'인간은 지금 위기 상황에 놓여있다.','pos_sentence':'인간__01/NNG 은/JX 지금__03/MAG 위기__01/NNG 상황__02/NNG 에/JKB 놓이/VV 어/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'포화 상태에 있는 용액을 말한다.','pos_sentence':'포화/NNG 상태__01/NNG 에/JKB 있/VV 는/ETM 용액/NNG 을/JKO 말__01/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'2년 후 수양대군은 왕위에 오른다.','pos_sentence':'2/SN 년__02/NNB 후__08/NNG 수양대군/NNP 은/JX 왕위__01/NNG 에/JKB 오르/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이젠 실전에 들어갔다.','pos_sentence':'이제__01/NNG ᆫ/JX 실전__04/NNG 에/JKB 들어가__01/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리 식구는 한참 동안 슬픔에 싸였다.','pos_sentence':'우리/NP 식구__01/NNG 는/JX 한참/NNG 동안__01/NNG 슬픔/NNG 에/JKB 싸이__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'장발에 떡 벌어진 어깨.','pos_sentence':'장발__03/NNG 에/JKB 떡__03/MAG 벌어지__01/VV ᆫ/ETM 어깨__01/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'연극마저도 그런 위기 상황에 처해 있다.','pos_sentence':'연극/NNG 마저/JX 도/JX 그런/MM 위기__01/NNG 상황__02/NNG 에/JKB 처하/VV 아/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'며칠째, 나는 불면에 시달렸다.','pos_sentence':'며칠/NNG 째/XSN ,/SP 나/NP 는/JX 불면__02/NNG 에/JKB 시달리/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'따라서 현실에 안주하려는 경향이 짙다.','pos_sentence':'따라서/MAJ 현실__02/NNG 에/JKB 안주__03/NNG 하/XSV 려는/ETM 경향__02/NNG 이/JKS 짙/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그녀는 오랜 침묵에 잠겨 있다.','pos_sentence':'그녀/NP 는/JX 오랜/MM 침묵/NNG 에/JKB 잠기__02/VV 어/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그 경우 펌프실 내부가 혼란에 빠진다.','pos_sentence':'그/MM 경우__03/NNG 펌프실/NNG 내부__04/NNG 가/JKS 혼란/NNG 에/JKB 빠지__02/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'젖이 부족하면 변비에 걸린다.','pos_sentence':'젖/NNG 이/JKS 부족__01/NNG 하/XSA 면/EC 변비/NNG 에/JKB 걸리__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'가난에 찌들어버렸어.','pos_sentence':'가난__01/NNG 에/JKB 찌들/VV 어/EC 버리/VX 었/EP 어/EF ./SF'},
{'name':'-에 (-ey)','sentence':'설악산도 비슷한 위기에 처해 있다.','pos_sentence':'설악산/NNP 도/JX 비슷/XR 하/XSA ᆫ/ETM 위기__01/NNG 에/JKB 처하/VV 아/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'호나우두는 8골로 대회 득점왕에 올랐다.','pos_sentence':'호나우두/NNP 는/JX 8/SN 골__14/NNG 로/JKB 대회__02/NNG 득점왕/NNG 에/JKB 오르/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'부인과 별거 상태에 있다.','pos_sentence':'부인__01/NNG 과/JKB 별거__02/NNG 상태__01/NNG 에/JKB 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리는 유엔과 각별한 관계에 있다.','pos_sentence':'우리/NP 는/JX 유엔/NNP 과/JKB 각별/NNG 하/XSA ᆫ/ETM 관계__05/NNG 에/JKB 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'각급 학교들이 방학에 들어갔다.','pos_sentence':'각급/NNG 학교/NNG 들/XSN 이/JKS 방학/NNG 에/JKB 들어가__01/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리 사회는 지금 과도기에 있다.','pos_sentence':'우리/NP 사회__07/NNG 는/JX 지금__03/MAG 과도기/NNG 에/JKB 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'나는 조금 이상한 감정에 사로잡혔다.','pos_sentence':'나/NP 는/JX 조금/MAG 이상__12/NNG 하/XSA ᆫ/ETM 감정__06/NNG 에/JKB 사로잡히/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이어 백악관도 비상에 들어갔다.','pos_sentence':'이어/MAG 백악관/NNP 도/JX 비상__01/NNG 에/JKB 들어가__01/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'서울지하철공사 노조가 7일 오전 부분파업에 들어간다.','pos_sentence':'서울지하철공사/NNP 노조__02/NNG 가/JKS 7/SN 일/NNB 오전__02/NNG 부분__01/NNG 파업/NNG 에/JKB 들어가__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그 때부터 남성은 배신감에 빠진다.','pos_sentence':'그/MM 때__01/NNG 부터/JX 남성__01/NNG 은/JX 배신감/NNG 에/JKB 빠지__02/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아마 회의에 빠져 있을 것이다.','pos_sentence':'아마/MAG 회의__05/NNG 에/JKB 빠지__02/VV 어/EC 있/VX 을/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 나는 더욱더 혼란에 빠져들었다.','pos_sentence':'그러나/MAJ 나/NP 는/JX 더욱더/MAG 혼란/NNG 에/JKB 빠지__02/VV 어/EC 들/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리는 공황상태에 빠졌어.','pos_sentence':'우리/NP 는/JX 공황__02/NNG 상태__01/NNG 에/JKB 빠지__02/VV 었/EP 어/EF ./SF'},
{'name':'-에 (-ey)','sentence':'경창종합학교 동료들은 수술비 모금 운동에 나섰다.','pos_sentence':'경창종합학교/NNP 동료/NNG 들/XSN 은/JX 수술비/NNG 모금/NNG 운동__02/NNG 에/JKB 나서/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그는 12월말부터 전국 순회공연에 들어간다.','pos_sentence':'그/NP 는/JX 12/SN 월말/NNG 부터/JX 전국__03/NNG 순회공연/NNG 에/JKB 들어가__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'드디어 여행길에 올랐다.','pos_sentence':'드디어/MAG 여행길/NNG 에/JKB 오르/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'다행히 나는 상위권에 속했다.','pos_sentence':'다행히/MAG 나/NP 는/JX 상위__01/NNG 권/XSN 에/JKB 속하__02/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'데뷔하자마자 정상에 올랐다.','pos_sentence':'데뷔/NNG 하/XSV 자마자/EC 정상__11/NNG 에/JKB 오르/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'내가 보는 세계 또한 허깨비에 불과하다.','pos_sentence':'내/NP 가/JKS 보__01/VV 는/ETM 세계__02/NNG 또한/MAG 허깨비__01/NNG 에/JKB 불과/MAG 하/XSA 다/EF ./SF'}]}
,{'postposition':'ey','function':'gol','sentences':[{'name':'-에 (-ey)','sentence':'중년 사내가 호주머니에 손을 찔렀다.','pos_sentence':'중년__01/NNG 사내__01/NNG 가/JKS 호주머니/NNG 에/JKB 손__01/NNG 을/JKO 찌르/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아기는 연탄을 언덕길에 내려놓았습니다.','pos_sentence':'아기__01/NNG 는/JX 연탄__03/NNG 을/JKO 언덕길/NNG 에/JKB 내려놓/VV 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그녀의 머리칼이 뺨에 달라붙었다.','pos_sentence':'그녀/NP 의/JKG 머리칼/NNG 이/JKS 뺨/NNG 에/JKB 달라붙/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'눈물이 한 방울 꽃다발의 가시에 떨어졌다.','pos_sentence':'눈물__01/NNG 이/JKS 한/MM 방울__01/NNG 꽃다발/NNG 의/JKG 가시__01/NNG 에/JKB 떨어지/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그녀의 손톱이 그의 팔에 박혔다.','pos_sentence':'그녀/NP 의/JKG 손톱__01/NNG 이/JKS 그/NP 의/JKG 팔__01/NNG 에/JKB 박히/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'훈련병이 땅바닥에 퍽 쓰러졌다.','pos_sentence':'훈련병/NNG 이/JKS 땅바닥/NNG 에/JKB 퍽__01/MAG 쓰러지/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그게 이제 경희 눈가에 붙었다.','pos_sentence':'그것/NP 이/JKS 이제/MAG 경희/NNP 눈가/NNG 에/JKB 붙/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'연출의 팔이 그의 어깨에 올라왔다.','pos_sentence':'연출__02/NNG 의/JKG 팔__01/NNG 이/JKS 그/NP 의/JKG 어깨__01/NNG 에/JKB 올라오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'서예계에 먹물이 튀었다.','pos_sentence':'서예__01/NNG 계/XSN 에/JKB 먹물/NNG 이/JKS 튀/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'최 서방은 들에 나갔다.','pos_sentence':'최/NNP 서방__02/NNG 은/JX 들__01/NNG 에/JKB 나가/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'먼저 책방에 갔어.','pos_sentence':'먼저/MAG 책방__01/NNG 에/JKB 가/VV 았/EP 어/EF ./SF'},
{'name':'-에 (-ey)','sentence':'한 발이 물 속에 빠졌다.','pos_sentence':'한/MM 발__01/NNG 이/JKS 물__01/NNG 속__01/NNG 에/JKB 빠지__02/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아버지는 형을 침대에 뉘었다.','pos_sentence':'아버지/NNG 는/JX 형__01/NNG 을/JKO 침대__02/NNG 에/JKB 뉘__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'마을에 방물장수가 들어왔다.','pos_sentence':'마을__01/NNG 에/JKB 방물장수/NNG 가/JKS 들어오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'나는 그녀의 몸뚱이 위에 엎어졌다.','pos_sentence':'나/NP 는/JX 그녀/NP 의/JKG 몸뚱이/NNG 위__01/NNG 에/JKB 엎어지/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그런데 하필 타구는 파울 라인 위에 떨어졌다.','pos_sentence':'그런데/MAJ 하필/MAG 타구__02/NNG 는/JX 파울/NNG 라인/NNG 위__01/NNG 에/JKB 떨어지/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'결론에 도달할 수 있다.','pos_sentence':'결론__02/NNG 에/JKB 도달__01/NNG 하/XSV ᆯ/ETM 수__02/NNB 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'언덕 꼭대기 외딴 구멍가게에 닿았습니다.','pos_sentence':'언덕/NNG 꼭대기/NNG 외딴/MM 구멍가게/NNG 에/JKB 닿/VV 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'9층에 다다른 것이었다.','pos_sentence':'9/SN 층__02/NNG 에/JKB 다다르/VV ᆫ/ETM 것/NNB 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러면 또다시 책장에 꽂혀버린다.','pos_sentence':'그러면/MAJ 또다시/MAG 책장__02/NNG 에/JKB 꽂히/VV 어/EC 버리/VX ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'오늘은 원장 2구에 갔다.','pos_sentence':'오늘/NNG 은/JX 원장__07/NNG 2/SN 구__15/NNG 에/JKB 가/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 선생님은 첨벙 물에 엎어졌습니다.','pos_sentence':'그러나/MAJ 선생__01/NNG 님/XSN 은/JX 첨벙/MAG 물__01/NNG 에/JKB 엎어지/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'춘기의 말은 이치에 닿았다.','pos_sentence':'춘기/NNP 의/JKG 말__01/NNG 은/JX 이치__06/NNG 에/JKB 닿/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그래서 자리에 누웠다.','pos_sentence':'그래서/MAJ 자리__02/NNG 에/JKB 눕__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그래서 사범대에 들어왔다.','pos_sentence':'그래서/MAJ 사범대/NNG 에/JKB 들어오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이윽고 약수터에 다다랐습니다.','pos_sentence':'이윽고/MAG 약수터/NNG 에/JKB 다다르/VV 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'누군가 학교에 신문을 가져왔다.','pos_sentence':'누구/NP 이/VCP ᆫ가/EC 학교/NNG 에/JKB 신문__10/NNG 을/JKO 가져오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'얼른 버스에 오르고 만다.','pos_sentence':'얼른/MAG 버스__02/NNG 에/JKB 오르/VV 고/EC 말/VX ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아마 목적지에 다다른 모양이었다.','pos_sentence':'아마/MAG 목적지/NNG 에/JKB 다다르/VV ᆫ/ETM 모양__02/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그래서 경화는 단도직입으로 본론에 들어갔다.','pos_sentence':'그래서/MAJ 경화/NNP 는/JX 단도직입/NNG 으로/JKB 본론/NNG 에/JKB 들어가__01/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'저녁 차로 대구에 갔다.','pos_sentence':'저녁/NNG 차__06/NNG 로/JKB 대구/NNP 에/JKB 가/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아이는 혜미 집에 가지 않았다.','pos_sentence':'아이__01/NNG 는/JX 혜미/NNP 집__01/NNG 에/JKB 가/VV 지/EC 않/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'가르시아는 그 열차에 올랐다.','pos_sentence':'가르시아/NNP 는/JX 그/MM 열차__02/NNG 에/JKB 오르/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'마침내 땅에 떨어진다.','pos_sentence':'마침내/MAG 땅/NNG 에/JKB 떨어지/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아내가 책장에 꽂아버린 것이다.','pos_sentence':'아내__01/NNG 가/JKS 책장__02/NNG 에/JKB 꽂/VV 아/EC 버리/VX ᆫ/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'수창이는 말없이 신문을 탁자 위에 던졌다.','pos_sentence':'수창이/NNP 는/JX 말없이/MAG 신문__10/NNG 을/JKO 탁자__01/NNG 위__01/NNG 에/JKB 던지/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이윽고 차는 호텔 앞에 닿았다.','pos_sentence':'이윽고/MAG 차__06/NNG 는/JX 호텔/NNG 앞/NNG 에/JKB 닿/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'마침내 그는 상자에 푹 거꾸러졌다.','pos_sentence':'마침내/MAG 그/NP 는/JX 상자__10/NNG 에/JKB 푹/MAG 거꾸러지/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'나는 술잔을 탁자에 올려놓았다.','pos_sentence':'나/NP 는/JX 술잔/NNG 을/JKO 탁자__01/NNG 에/JKB 올려놓/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아래층의 시멘트 바닥에 창길을 내동댕이쳤다.','pos_sentence':'아래층/NNG 의/JKG 시멘트/NNG 바닥__01/NNG 에/JKB 창길/NNP 을/JKO 내동댕이치/VV 었/EP 다/EF ./SF'}]}
,{'postposition':'ey','function':'ins','sentences':[{'name':'-에 (-ey)','sentence':'아저씨 눈물이 달빛에 방울방울 보였습니다.','pos_sentence':'아저씨/NNG 눈물__01/NNG 이/JKS 달빛/NNG 에/JKB 방울방울/NNG 보이__01/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'초겨울이 바람에 날리고 있었다.','pos_sentence':'초겨울/NNG 이/JKS 바람__01/NNG 에/JKB 날리__01/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'손등이 가시에 긁혀 나갔다.','pos_sentence':'손등__01/NNG 이/JKS 가시__01/NNG 에/JKB 긁히/VV 어/EC 나가/VX 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'밑실이 반달에 감겼을 때','pos_sentence':'밑실/NNG 이/JKS 반달__01/NNG 에/JKB 감기__02/VV 었/EP 을/ETM 때__01/NNG'},
{'name':'-에 (-ey)','sentence':'사람들이 들것에 부인을 실었다.','pos_sentence':'사람/NNG 들/XSN 이/JKS 들것/NNG 에/JKB 부인__04/NNG 을/JKO 싣/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'황산, 질산, 수산화칼륨에 녹는다.','pos_sentence':'황산/NNG ,/SP 질산/NNG ,/SP 수산화칼륨/NNG 에/JKB 녹/VV 는다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'말에 짓밟힌 부상 때문이 아니었다.','pos_sentence':'말__05/NNG 에/JKB 짓밟히/VV ᆫ/ETM 부상__05/NNG 때문/NNB 이/JKC 아니/VCN 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그는 망연자실, 도깨비에 홀린 듯.','pos_sentence':'그/NP 는/JX 망연자실/NNG ,/SP 도깨비/NNG 에/JKB 홀리/VV ᆫ/ETM 듯/NNB ./SF'},
{'name':'-에 (-ey)','sentence':'플루오르화수소에 의하여 분해된다.','pos_sentence':'플루오르화수소/NNG 에/JKB 의하/VV 아/EC 분해/NNG 되/XSV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그의 뒷모습은 금방 어둠에 묻혔다.','pos_sentence':'그/NP 의/JKG 뒷모습/NNG 은/JX 금방/MAG 어둠/NNG 에/JKB 묻히__02/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'불빛에 살펴보니 태봉이었다.','pos_sentence':'불빛/NNG 에/JKB 살펴보/VV 니/EC 태봉/NNP 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'베일에 쌓인 바이롬사','pos_sentence':'베일/NNG 에/JKB 쌓이/VV ᆫ/ETM 바이롬사/NNP'},
{'name':'-에 (-ey)','sentence':'온몸이 금세 비에 젖었다.','pos_sentence':'온몸/NNG 이/JKS 금세/MAG 비__01/NNG 에/JKB 젖__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'덫에 앞발을 찌긴 것이었다.','pos_sentence':'덫/NNG 에/JKB 앞발/NNG 을/JKO 찧기/VV ᆫ/ETM 것/NNB 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'번데기들이 핏물에 잠기고 있었다.','pos_sentence':'번데기__01/NNG 들/XSN 이/JKS 핏물/NNG 에/JKB 잠기__02/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'주위는 완전히 어둠에 묻혔다.','pos_sentence':'주위__02/NNG 는/JX 완전히/MAG 어둠/NNG 에/JKB 묻히__02/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'비누방울에 반사되어 무지개를 만들던 햇살.','pos_sentence':'비누/NNG 방울__01/NNG 에/JKB 반사__01/NNG 되/XSV 어/EC 무지개/NNG 를/JKO 만들/VV 던/ETM 햇살/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'이들은 모두 투표에 의해 선출된다.','pos_sentence':'이/NP 들/XSN 은/JX 모두/MAG 투표__01/NNG 에/JKB 의하/VV 아/EC 선출__02/NNG 되/XSV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'양념장에 무친다.','pos_sentence':'양념장/NNG 에/JKB 무치/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'감자도 신문지에 싸서 보관.','pos_sentence':'감자__01/NNG 도/JX 신문지/NNG 에/JKB 싸__01/VV 아서/EC 보관__01/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'바람에 찢겨','pos_sentence':'바람__01/NNG 에/JKB 찢기__01/VV 어/EC'},
{'name':'-에 (-ey)','sentence':'나는 초대장의 명령에 휘둘리고 있었다.','pos_sentence':'나/NP 는/JX 초대장/NNG 의/JKG 명령__01/NNG 에/JKB 휘둘리/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그런 책 다 불에 태워 버려라.','pos_sentence':'그런/MM 책__01/NNG 다/MAG 불__01/NNG 에/JKB 태우__01/VV 어/EC 버리/VX 어라/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러면 바퀴에 콱 치이고 말지.','pos_sentence':'그러면/MAJ 바퀴__01/NNG 에/JKB 콱/MAG 치이__03/VV 고/EC 말/VX 지/EF ./SF'},
{'name':'-에 (-ey)','sentence':'먹구름에 싸인 물욕의 폐허.','pos_sentence':'먹구름/NNG 에/JKB 싸이__01/VV ᆫ/ETM 물욕__02/NNG 의/JKG 폐허__02/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'이 장면이 카메라에 잡혔다.','pos_sentence':'이__05/MM 장면__04/NNG 이/JKS 카메라/NNG 에/JKB 잡히__02/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그녀는 가슴이 바늘에 찔리는 느낌이다.','pos_sentence':'그녀/NP 는/JX 가슴__01/NNG 이/JKS 바늘/NNG 에/JKB 찔리/VV 는/ETM 느낌/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'내 총에 맞은 거야.','pos_sentence':'나/NP 의/JKG 총__03/NNG 에/JKB 맞__03/VV 은/ETM 거/NNB 이/VCP 야/EF ./SF'},
{'name':'-에 (-ey)','sentence':'새롬이는 산딸기를 풀줄기에 꿰었습니다.','pos_sentence':'새롬이/NNP 는/JX 산딸기/NNG 를/JKO 풀__02/NNG 줄기__01/NNG 에/JKB 꿰/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그건 벌써 땀에 젖어 있었다.','pos_sentence':'그것/NP ᆫ/JX 벌써/MAG 땀__01/NNG 에/JKB 젖__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그것들을 보자기에 쌌다.','pos_sentence':'그것/NP 들/XSN 을/JKO 보자기__02/NNG 에/JKB 싸__01/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그녀는 그런 맛에 산다.','pos_sentence':'그녀/NP 는/JX 그런/MM 맛__01/NNG 에/JKB 살__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'바람결에 꽃향내가 날아왔다.','pos_sentence':'바람결/NNG 에/JKB 꽃향내/NNG 가/JKS 날아오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'낙엽이 불길에 사그러드는 냄새 때문일까?','pos_sentence':'낙엽/NNG 이/JKS 불길/NNG 에/JKB 사그러들/VV 는/ETM 냄새/NNG 때문/NNB 이/VCP ᆯ까/EF ?/SF'},
{'name':'-에 (-ey)','sentence':'비닐 봉투나 지퍼백 등에 넣어 냉동한다.','pos_sentence':'비닐/NNG 봉투__02/NNG 나/JC 지퍼백/NNG 등__05/NNB 에/JKB 넣/VV 어/EC 냉동/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'온동네는 아득한 매향에 휩싸인다.','pos_sentence':'온/MM 동네/NNG 는/JX 아득/XR 하/XSA ᆫ/ETM 매향__02/NNG 에/JKB 휩싸이/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그들은 그 향기에 취해 있었다.','pos_sentence':'그/NP 들/XSN 은/JX 그/MM 향기__01/NNG 에/JKB 취하__03/VV 아/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'총에 맞은 것이지요.','pos_sentence':'총__03/NNG 에/JKB 맞__03/VV 은/ETM 것/NNB 이/VCP 지요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'두환은 총에 맞았다.','pos_sentence':'두환/NNP 은/JX 총__03/NNG 에/JKB 맞__03/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그래서 그는 절대 말에 넘어가지 않는다.','pos_sentence':'그래서/MAJ 그/NP 는/JX 절대/MAG 말__01/NNG 에/JKB 넘어가__01/VV 지/EC 않/VX 는다/EF ./SF'}]}
,{'postposition':'ey','function':'loc','sentences':[{'name':'-에 (-ey)','sentence':'보주성 거란이 압록강 동쪽 연안에 쌓은 성.','pos_sentence':'보주성/NNP 거란/NNP 이/JKS 압록강/NNP 동쪽/NNG 연안__02/NNG 에/JKB 쌓/VV 은/ETM 성__08/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'마침 총무님이 사무실에 남아 있었다.','pos_sentence':'마침/MAG 총무/NNG 님/XSN 이/JKS 사무실/NNG 에/JKB 남/VV 아/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'거실에 불이 켜져 있었다.','pos_sentence':'거실__02/NNG 에/JKB 불__01/NNG 이/JKS 켜__01/VV 어/EC 지/VX 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'개울 옆 언덕 밑에 샘물이 졸졸졸 흘렀습니다.','pos_sentence':'개울/NNG 옆/NNG 언덕/NNG 밑__01/NNG 에/JKB 샘물/NNG 이/JKS 졸졸졸/MAG 흐르__01/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'옥점의 코밑에 땀방울이 방울방울 맺혔다.','pos_sentence':'옥점/NNP 의/JKG 코밑/NNG 에/JKB 땀방울/NNG 이/JKS 방울방울/NNG 맺히/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그녀의 이마에 땀이 송골송골 맺혔다.','pos_sentence':'그녀/NP 의/JKG 이마__01/NNG 에/JKB 땀__01/NNG 이/JKS 송골송골/MAG 맺히/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리 동네 앞길에 택시 정류장이 하나 있다.','pos_sentence':'우리/NP 동네/NNG 앞길__01/NNG 에/JKB 택시/NNG 정류장/NNG 이/JKS 하나/NR 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'남산 꼭대기에 횃불이 빤히 비쳤다.','pos_sentence':'남산/NNP 꼭대기/NNG 에/JKB 횃불/NNG 이/JKS 빤히/MAG 비치__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'소내에 긴장감이 감돌기 시작했다.','pos_sentence':'소__09/NNG 내/NNB 에/JKB 긴장감/NNG 이/JKS 감돌/VV 기/ETN 시작__01/NNG 하/XSV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'해수욕장에 범선(帆船)이 하나 띄었다.','pos_sentence':'해수욕장/NNG 에/JKB 범선/NNG (/SS 帆船/SH )/SS 이/JKS 하나/NR 띄/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'바다에 어둠이 깔리고 있다.','pos_sentence':'바다/NNG 에/JKB 어둠/NNG 이/JKS 깔리__01/VV 고/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'방바닥에 짜장면 두 그릇이 놓여 있었다.','pos_sentence':'방바닥/NNG 에/JKB 짜장면/NNG 두/MM 그릇/NNG 이/JKS 놓이/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'밤하늘에 별이 떠 있었다.','pos_sentence':'밤하늘/NNG 에/JKB 별/NNG 이/JKS 뜨__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'손바닥, 발바닥에 홍반이 나타나기도 한다.','pos_sentence':'손바닥/NNG ,/SP 발바닥/NNG 에/JKB 홍반/NNG 이/JKS 나타나/VV 기/ETN 도/JX 하/VX ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'교실에 자신이 서 있다고 생각하여라.','pos_sentence':'교실/NNG 에/JKB 자신__01/NNG 이/JKS 서/VV 어/EC 있/VX 다고/EC 생각__01/NNG 하/XSV 아라/EF ./SF'},
{'name':'-에 (-ey)','sentence':'미루나무 꼭대기에 조각 구름이 걸려 있네.','pos_sentence':'미루나무/NNG 꼭대기/NNG 에/JKB 조각__01/NNG 구름__01/NNG 이/JKS 걸리__01/VV 어/EC 있/VX 네/EF ./SF'},
{'name':'-에 (-ey)','sentence':'마을에 불이 났다.','pos_sentence':'마을__01/NNG 에/JKB 불__01/NNG 이/JKS 나/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'손에 땟국물이 잔뜩 묻어 있다.','pos_sentence':'손__01/NNG 에/JKB 땟국물/NNG 이/JKS 잔뜩/MAG 묻__01/VV 어/EC 있/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'갈론마을에 민박집이 세 집 있다.','pos_sentence':'갈론마을/NNP 에/JKB 민박/NNG 집__01/NNG 이/JKS 세/MM 집__01/NNG 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우선 우리나라의 수도 서울에 시립 박물관이 없다.','pos_sentence':'우선/MAG 우리나라/NNG 의/JKG 수도__09/NNG 서울/NNP 에/JKB 시립__01/NNG 박물관/NNG 이/JKS 없/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'서창에 달빛이 앉아 있었다.','pos_sentence':'서창__03/NNG 에/JKB 달빛/NNG 이/JKS 앉/VV 아/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'탁자 앞에 앉았다.','pos_sentence':'탁자__01/NNG 앞/NNG 에/JKB 앉/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그는 강 건너에 있다.','pos_sentence':'그/NP 는/JX 강__01/NNG 건너__01/NNG 에/JKB 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'봉화군 경상 북도 북쪽 끝에 있는 군.','pos_sentence':'봉화군/NNP 경상/NNP 북도/NNG 북쪽/NNG 끝__01/NNG 에/JKB 있/VV 는/ETM 군__06/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'당나귀의 코끝에 홍당무를 매달아놓는다.','pos_sentence':'당나귀/NNG 의/JKG 코끝/NNG 에/JKB 홍당무/NNG 를/JKO 매달/VV 아/EC 놓/VX 는다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그의 화실은 신촌에 있다.','pos_sentence':'그/NP 의/JKG 화실__04/NNG 은/JX 신촌/NNP 에/JKB 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'다시 한 번 무대 위에 서고 싶다.','pos_sentence':'다시/MAG 한/MM 번/NNB 무대__06/NNG 위__01/NNG 에/JKB 서/VV 고/EC 싶/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'인근에 석탄박물관,성주산 휴양림 등이 있다.','pos_sentence':'인근/NNG 에/JKB 석탄/NNG 박물관/NNG ,/SP 성주산/NNP 휴양림/NNG 등__05/NNB 이/JKS 있/VV 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'뒤쪽에 금강산 경치도 기가 맥히더라.','pos_sentence':'뒤쪽__01/NNG 에/JKB 금강산/NNP 경치__02/NNG 도/JX 기__13/NNG 가/JKS 맥히/VV 더라/EF ./SF'},
{'name':'-에 (-ey)','sentence':'제가 문화원 l층 라운지에 서 있더군요.','pos_sentence':'제/NP 가/JKS 문화원/NNG l/SL 층__02/NNG 라운지/NNG 에/JKB 서/VV 어/EC 있/VX 더군요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'밴쿠버 캐나다 남서부의 태평양 연안에 있는 항구 도시.','pos_sentence':'밴쿠버/NNP 캐나다/NNP 남서부/NNG 의/JKG 태평양/NNP 연안__02/NNG 에/JKB 있/VV 는/ETM 항구__03/NNG 도시__03/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'아직도 이곳 벌교 바닥에 사는지 어쩐지.','pos_sentence':'아직/MAG 도/JX 이곳/NP 벌교/NNP 바닥__01/NNG 에/JKB 살__01/VV 는지/EC 어쩐지/MAG ./SF'},
{'name':'-에 (-ey)','sentence':'산지촌 산지에 모여 있는 마을.','pos_sentence':'산지촌/NNG 산지/NNG 에/JKB 모이/VV 어/EC 있/VX 는/ETM 마을__01/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'숲속에 사는 코알라','pos_sentence':'숲__01/NNG 속__01/NNG 에/JKB 살__01/VV 는/ETM 코알라/NNG'},
{'name':'-에 (-ey)','sentence':'둘 다 얼굴에 상처 자국이 많았다.','pos_sentence':'둘/NR 다/MAG 얼굴/NNG 에/JKB 상처__02/NNG 자국__01/NNG 이/JKS 많/VA 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'과연 이 우주에는 끝이 있을까요?','pos_sentence':'과연__01/MAG 이/MM 우주__02/NNG 에/JKB 는/JX 끝/NNG 이/JKS 있/VV 을까요/EF ?/SF'},
{'name':'-에 (-ey)','sentence':'우리 집은 골목 어귀에 있었어.','pos_sentence':'우리/NP 집__01/NNG 은/JX 골목__01/NNG 어귀__01/NNG 에/JKB 있/VV 었/EP 어/EF ./SF'},
{'name':'-에 (-ey)','sentence':'담배는 책 옆에 얌전히 있었다.','pos_sentence':'담배/NNG 는/JX 책__01/NNG 옆/NNG 에/JKB 얌전히/MAG 있/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'사모예드족 소련의 시베리아 북서부에 사는 수렵, 목축민.','pos_sentence':'사모예드족/NNP 소련/NNP 의/JKG 시베리아/NNP 북서부/NNG 에/JKB 살__01/VV 는/ETM 수렵/NNG ,/SP 목축민/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'수안보 온천 충청 북도 중원군 상모면 온천리에 있는 온천.','pos_sentence':'수안보/NNP 온천__02/NNG 충청/NNP 북도/NNP 중원군/NNP 상모면/NNP 온천리/NNP 에/JKB 있/VV 는/ETM 온천__02/NNG ./SF'}]}
,{'postposition':'ey','function':'thm','sentences':[{'name':'-에 (-ey)','sentence':'콩 씨에 잎이 나왔습니다.','pos_sentence':'콩/NNG 씨__01/NNG 에/JKB 잎/NNG 이/JKS 나오/VV 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'어머니의 편지에 그런 말이 없었던가?','pos_sentence':'어머니/NNG 의/JKG 편지__02/NNG 에/JKB 그런/MM 말__01/NNG 이/JKS 없/VA 었/EP 던가/EF ?/SF'},
{'name':'-에 (-ey)','sentence':'다리에 금이 갔어요.','pos_sentence':'다리__01/NNG 에/JKB 금__02/NNG 이/JKS 가/VV 았/EP 어요/EF ./SF'},
{'name':'-에 (-ey)','sentence':'자기 주장에 대한 자긍심.','pos_sentence':'자기/NP 주장__03/NNG 에/JKB 대하__02/VV ᆫ/ETM 자긍심/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'영화에 대한 뒤아멜의 정의이다.','pos_sentence':'영화__01/NNG 에/JKB 대하__02/VV ᆫ/ETM 뒤아멜/NNP 의/JKG 정의__05/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 우리는 곧 푸들에 싫증이 났다.','pos_sentence':'그러나/MAJ 우리/NP 는/JX 곧/MAG 푸들/NNG 에/JKB 싫증/NNG 이/JKS 나/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'국어에 대한 충성심이 곧 애국심이다.','pos_sentence':'국어/NNG 에/JKB 대하__02/VV ᆫ/ETM 충성심/NNG 이/JKS 곧/MAG 애국심/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'채송화 꽃에 꽃이 피기 시작했습니다.','pos_sentence':'채송화/NNG 꽃__01/NNG 에/JKB 꽃__01/NNG 이/JKS 피__01/VV 기/ETN 시작__01/NNG 하/XSV 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'봉선화에 잎이 나왔습니다.','pos_sentence':'봉선화/NNG 에/JKB 잎/NNG 이/JKS 나오/VV 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'한탄하는 것이 실록에 나옵니다.','pos_sentence':'한탄/NNG 하/XSV 는/ETM 것/NNB 이/JKS 실록/NNG 에/JKB 나오/VV ᄇ니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'학술 연구에 대한 최고의 학위이다.','pos_sentence':'학술/NNG 연구__03/NNG 에/JKB 대하__02/VV ᆫ/ETM 최고__02/NNG 의/JKG 학위/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'차라리 열무김치에 보리밥이 낫지 싶다.','pos_sentence':'차라리/MAG 열무김치/NNG 에/JKB 보리밥/NNG 이/JKS 낫__02/VA 지/EC 싶/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'문명에 대한 반항이기도 하다.','pos_sentence':'문명__03/NNG 에/JKB 대하__02/VV ᆫ/ETM 반항__01/NNG 이/VCP 기/ETN 도/JX 하/VX 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'과일에는 영양가가 별로 없다.','pos_sentence':'과일__01/NNG 에/JKB 는/JX 영양가/NNG 가/JKS 별로/MAG 없/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'외지의 지주는 농사에 관심이 없다.','pos_sentence':'외지__03/NNG 의/JKG 지주__03/NNG 는/JX 농사__01/NNG 에/JKB 관심__01/NNG 이/JKS 없/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'옷에 이슬이 묻어 있었다.','pos_sentence':'옷/NNG 에/JKB 이슬/NNG 이/JKS 묻__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그때 갑자기 골목 외등에 불이 들어왔다.','pos_sentence':'그때/NNG 갑자기/MAG 골목__01/NNG 외등__02/NNG 에/JKB 불__01/NNG 이/JKS 들어오/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'감동 어떤 사물에 대한 느낌의 반응.','pos_sentence':'감동__02/NNG 어떤/MM 사물__10/NNG 에/JKB 대하__02/VV ᆫ/ETM 느낌/NNG 의/JKG 반응/NNG ./SF'},
{'name':'-에 (-ey)','sentence':'커피색 얼룩이 벽지에 남는다.','pos_sentence':'커피색/NNG 얼룩/NNG 이/JKS 벽지__01/NNG 에/JKB 남/VV 는다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 선거에 대한 관심은 너무나 저조하다.','pos_sentence':'그러나/MAJ 선거__04/NNG 에/JKB 대하__02/VV ᆫ/ETM 관심__01/NNG 은/JX 너무나/MAG 저조__02/NNG 하/XSA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'식사에 대한 문제도 마찬가지다.','pos_sentence':'식사__03/NNG 에/JKB 대하__02/VV ᆫ/ETM 문제__06/NNG 도/JX 마찬가지/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'사회 진출에 대한 정보도 필요하겠다.','pos_sentence':'사회__07/NNG 진출__02/NNG 에/JKB 대하__02/VV ᆫ/ETM 정보__06/NNG 도/JX 필요/NNG 하/XSA 겠/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 독감에는 특효약이 없다.','pos_sentence':'그러나/MAJ 독감__01/NNG 에/JKB 는/JX 특효약/NNG 이/JKS 없/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'담에 금이 갔다.','pos_sentence':'담__01/NNG 에/JKB 금__02/NNG 이/JKS 가/VV 았/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'돈에 세상이 다 담겨 있더라.','pos_sentence':'돈__01/NNG 에/JKB 세상__01/NNG 이/JKS 다/MAG 담기__01/VV 어/EC 있/VX 더라/EF ./SF'},
{'name':'-에 (-ey)','sentence':'생명의 힘에는 불가능이 없다.','pos_sentence':'생명/NNG 의/JKG 힘__01/NNG 에/JKB 는/JX 불/XPN 가능/XR 이/JKS 없/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그러나 요즈음의 대중가요에는 그런 것이 없다.','pos_sentence':'그러나/MAJ 요즈음/NNG 의/JKG 대중가요/NNG 에/JKB 는/JX 그런/MM 것/NNB 이/JKS 없/VA 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'세호의 아버지는 담배에 불을 붙였습니다.','pos_sentence':'세호/NNP 의/JKG 아버지/NNG 는/JX 담배/NNG 에/JKB 불__01/NNG 을/JKO 붙이/VV 었/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'모든 고백에는 고통이 따른다.','pos_sentence':'모든/MM 고백/NNG 에/JKB 는/JX 고통/NNG 이/JKS 따르__01/VV ᆫ다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'우리말에 진퇴양난과 같은 경우이다.','pos_sentence':'우리말/NNG 에/JKB 진퇴양난/NNG 과/JKB 같/VA 은/ETM 경우__03/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'삶에 모범 답안은 없어.','pos_sentence':'삶/NNG 에/JKB 모범__02/NNG 답안/NNG 은/JX 없/VA 어/EF ./SF'},
{'name':'-에 (-ey)','sentence':'상덕은 석유램프에 불을 켰다.','pos_sentence':'상덕/NNP 은/JX 석유__01/NNG 램프__01/NNG 에/JKB 불__01/NNG 을/JKO 켜__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'아버지는 가마솥에 장작불을 지피고 있었다.','pos_sentence':'아버지/NNG 는/JX 가마솥/NNG 에/JKB 장작불/NNG 을/JKO 지피__02/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'다음은 관광 산업에 관한 책이다.','pos_sentence':'다음__01/NNG 은/JX 관광__02/NNG 산업/NNG 에/JKB 관하__02/VV ᆫ/ETM 책__01/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이 글은 그것에 대한 고백입니다.','pos_sentence':'이__05/MM 글/NNG 은/JX 그것/NP 에/JKB 대하__02/VV ᆫ/ETM 고백/NNG 이/VCP ᄇ니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'대중들을 위한 문화에 등한했습니다.','pos_sentence':'대중__02/NNG 들/XSN 을/JKO 위하__01/VV ᆫ/ETM 문화__01/NNG 에/JKB 등한/XR 하/XSA 았/EP 습니다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'이 말은 연애에 관한 진리다.','pos_sentence':'이/MM 말__01/NNG 은/JX 연애__05/NNG 에/JKB 관하__02/VV ᆫ/ETM 진리/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'그리고 로렌츠 변환식에 대해서도 불변이다.','pos_sentence':'그리고/MAJ 로렌츠/NNP 변환식/NNG 에/JKB 대하__02/VV 아서/EC 도/JX 불변__02/NNG 이/VCP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'영순이는 갑자기 다리에 힘이 쭉 빠졌다.','pos_sentence':'영순이/NNP 는/JX 갑자기/MAG 다리__01/NNG 에/JKB 힘__01/NNG 이/JKS 쭉/MAG 빠지__01/VV 었/EP 다/EF ./SF'},
{'name':'-에 (-ey)','sentence':'정빈에 관한 아버지의 설명이다.','pos_sentence':'정빈/NNP 에/JKB 관하__02/VV ᆫ/ETM 아버지/NNG 의/JKG 설명/NNG 이/VCP 다/EF ./SF'}]}
,{'postposition':'eyse','function':'loc','sentences':[{'name':'-에서 (-eyse)','sentence':'우리 공동체 마을 아이들이 학교에서 공부하는 시간은 아주 적다.','pos_sentence':'우리/NP 공동체/NNG 마을__01/NNG 아이__01/NNG 들/XSN 이/JKS 학교/NNG 에서/JKB 공부__01/NNG 하/XSV 는/ETM 시간__04/NNG 은/JX 아주/MAG 적/VA 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'한 청소년이 사이코드라마에서 이런 대사를 했다.','pos_sentence':'한/MM 청소년/NNG 이/JKS 사이코드라마/NNG 에서/JKB 이런/MM 대사__17/NNG 를/JKO 하/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'이것들이 전국 도처에서 굴러다니다 보니 차량 사고가 빈발한다.','pos_sentence':'이것/NP 들/XSN 이/JKS 전국__03/NNG 도처/NNG 에서/JKB 굴러다니/VV 다/EC 보/VX 니/EC 차량__01/NNG 사고__12/NNG 가/JKS 빈발__01/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'문법이 시험에서 차지하는 비중은 20% 정도 된다.','pos_sentence':'문법__01/NNG 이/JKS 시험__03/NNG 에서/JKB 차지__01/NNG 하/XSV 는/ETM 비중/NNG 은/JX 20/SN %/SW 정도__11/NNG 되__01/VV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'대중적 차원에서 생명이, 생기가 흐르게 해야 한다.','pos_sentence':'대중__02/NNG 적/XSN 차원__01/NNG 에서/JKB 생명/NNG 이/JKS ,/SP 생기__01/NNG 가/JKS 흐르__01/VV 게/EC 하/VX 아야/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'개 콘테스트에서 심사위원들이 그런 시험을 해본다더군요.','pos_sentence':'개__03/NNG 콘테스트/NNG 에서/JKB 심사__08/NNG 위원__01/NNG 들/XSN 이/JKS 그런/MM 시험__03/NNG 을/JKO 하/VV 아/EC 보/VX ᆫ다더군요/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'사계명 천도교에서 교인들이 마땅히 지켜야 할 네 가지 계율.','pos_sentence':'사계명/NNG 천도교/NNG 에서/JKB 교인__04/NNG 들/XSN 이/JKS 마땅히/MAG 지키__01/VV 어야/EC 하/VX ᆯ/ETM 네__02/MM 가지/NNB 계율__01/NNG ./SF'},
{'name':'-에서 (-eyse)','sentence':'경험상 이름자에서 이런 괘상이 나오면 결혼관계가 불행하다.','pos_sentence':'경험/NNG 상/XSN 이름자/NNG 에서/JKB 이런/MM 괘상/NNG 이/JKS 나오/VV 면/EC 결혼/NNG 관계__05/NNG 가/JKS 불행/NNG 하/XSA 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'방청석에서 사람들이 환호를 하고 있었다.','pos_sentence':'방청석/NNG 에서/JKB 사람/NNG 들/XSN 이/JKS 환호__04/NNG 를/JKO 하/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'씨앗에서 잎과 꽃이 피기 시작하는 계절을 의미한다.','pos_sentence':'씨앗/NNG 에서/JKB 잎/NNG 과/JC 꽃__01/NNG 이/JKS 피__01/VV 기/ETN 시작__01/NNG 하/XSV 는/ETM 계절__02/NNG 을/JKO 의미/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'한국이 드디어 월드컵 축구대회 본선 무대에서 첫 승리를 거두었다.','pos_sentence':'한국/NNP 이/JKS 드디어/MAG 월드컵/NNG 축구__04/NNG 대회__02/NNG 본선__03/NNG 무대__06/NNG 에서/JKB 첫/MM 승리/NNG 를/JKO 거두/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'몇달 전 바로 이 앞동에서 여학생이 투신을 했다.','pos_sentence':'몇/MM 달__05/NNG 전__08/NNG 바로/MAG 이/MM 앞/NNG 동__15/NNB 에서/JKB 여학생/NNG 이/JKS 투신__01/NNG 을/JKO 하/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'피아니스트 이지민이 11일 오후 8시 금호아트홀에서 리사이틀을 갖는다.','pos_sentence':'피아니스트/NNG 이지민/NNP 이/JKS 11/SN 일/NNB 오후__02/NNG 8/SN 시/NNB 금호/NNP 아트홀/NNG 에서/JKB 리사이틀/NNG 을/JKO 갖/VV 는다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'바람이 폐선 모서리에서 휘파람 소리를 냈다.','pos_sentence':'바람__01/NNG 이/JKS 폐선__01/NNG 모서리__01/NNG 에서/JKB 휘파람/NNG 소리__01/NNG 를/JKO 내__02/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'인간은 그 자신이 우주에서 고립되었다고 느끼고 있다.','pos_sentence':'인간__01/NNG 은/JX 그/MM 자신__01/NNG 이/JKS 우주__02/NNG 에서/JKB 고립__01/NNG 되/XSV 었/EP 다고/EC 느끼__02/VV 고/EC 있/VX 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'이러한 상황에서 특히 한-중 국방장관 회담이 눈길을 끈다.','pos_sentence':'이러/XR 하/XSA ᆫ/ETM 상황__02/NNG 에서/JKB 특히/MAG 한/NNP -/SS 중/NNP 국방장관/NNG 회담/NNG 이/JKS 눈길__01/NNG 을/JKO 끌/VV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'민주 세력이 선거에서 승리한다는 보장은 어디에도 없었다.','pos_sentence':'민주__02/NNG 세력/NNG 이/JKS 선거__04/NNG 에서/JKB 승리/NNG 하/XSV ᆫ다는/ETM 보장/NNG 은/JX 어디/NP 에/JKB 도/JX 없/VA 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'홀에서 윤 마담이 다희를 불렀다.','pos_sentence':'홀__06/NNG 에서/JKB 윤/NNP 마담/NNG 이/JKS 다희/NNP 를/JKO 부르/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'남편이 회사에서 보너스를 탔다.','pos_sentence':'남편__01/NNG 이/JKS 회사__04/NNG 에서/JKB 보너스/NNG 를/JKO 타__04/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'한 집에서 가격이 내렸다.','pos_sentence':'한/MM 집__01/NNG 에서/JKB 가격__03/NNG 이/JKS 내리/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'솔직히 요즘처럼 직장에서 혁신이 강조된 적도 없었다.','pos_sentence':'솔직히/MAG 요즘/NNG 처럼/JKB 직장__05/NNG 에서/JKB 혁신/NNG 이/JKS 강조__02/NNG 되/XSV ᆫ/ETM 적__03/NNB 도/JX 없/VA 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'이 미당이 최근 어느 시낭송 모임에서 이런 인사말을 했다.','pos_sentence':'이__05/MM 미당/NNP 이/JKS 최근/NNG 어느/MM 시__13/NNG 낭송/NNG 모임__01/NNG 에서/JKB 이런/MM 인사말/NNG 을/JKO 하/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'야구 메이저리그에서 승부조작이 벌어지면 즉각 영구 추방이 결정된다.','pos_sentence':'야구__02/NNG 메이저__88/NNG 리그__01/NNG 에서/JKB 승부__03/NNG 조작__02/NNG 이/JKS 벌어지__02/VV 면/EC 즉각/MAG 영구__01/NNG 추방__02/NNG 이/JKS 결정__01/NNG 되/XSV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'언제부턴가 아이들은 놀이터에서 놀지 않았다.','pos_sentence':'언제/NP 부터/JX 이/VCP ᆫ가/EC 아이__01/NNG 들/XSN 은/JX 놀이터/NNG 에서/JKB 놀/VV 지/EC 않/VX 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'고향에서 결혼하고 아이를 낳았다.','pos_sentence':'고향__02/NNG 에서/JKB 결혼/NNG 하/XSV 고/EC 아이__01/NNG 를/JKO 낳__01/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'가네마루의 대답은 한국에서 자주 듣던 소리다.','pos_sentence':'가네마루/NNP 의/JKG 대답/NNG 은/JX 한국/NNP 에서/JKB 자주/MAG 듣__01/VV 던/ETM 소리__01/NNG 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그 여자는 산밭에서 혼자서 일을 하고 있었다.','pos_sentence':'그/MM 여자__02/NNG 는/JX 산밭/NNG 에서/JKB 혼자__01/NNG 서/JKS 일__01/NNG 을/JKO 하/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'나는 하와이에서 진정 용기 있는 인생을 목격한 것이다.','pos_sentence':'나/NP 는/JX 하와이/NNP 에서/JKB 진정/MAG 용기__02/NNG 있/VV 는/ETM 인생__01/NNG 을/JKO 목격/NNG 하/XSV ᆫ/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'자민당 내에서 파벌에 속하지 않은 의원은 15명이다.','pos_sentence':'자민당/NNP 내/NNB 에서/JKB 파벌__01/NNG 에/JKB 속하__02/VV 지/EC 않/VX 은/ETM 의원__05/NNG 은/JX 15/SN 명/NNB 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'무엇인가 그녀의 가슴속에서 갈가리 찢겨져 나갔다.','pos_sentence':'무엇/NP 이/VCP ᆫ가/EC 그녀/NP 의/JKG 가슴속/NNG 에서/JKB 갈가리/MAG 찢기__01/VV 어/EC 지/VX 어/EC 나가/VX 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'대한극장 옆 다방에서 만나기로 했던 것이다.','pos_sentence':'대한극장/NNP 옆/NNG 다방__02/NNG 에서/JKB 만나/VV 기/ETN 로/JKB 하/VX 았/EP 던/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'저와는 벨기에에서 처음 만났었죠.','pos_sentence':'저/NP 와/JKB 는/JX 벨기에/NNP 에서/JKB 처음/NNG 만나/VV 았었/EP 죠/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그때 원소에서 빨래하던 선비가 보인다.','pos_sentence':'그때/NNG 원소/NNP 에서/JKB 빨래/NNG 하/XSV 던/ETM 선비/NNP 가/JKS 보이__01/VV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'형의 문장이 입 안에서 자꾸만 맴돌았다.','pos_sentence':'형__01/NNG 의/JKG 문장__02/NNG 이/JKS 입/NNG 안__01/NNG 에서/JKB 자꾸/MAG 만/JX 맴돌/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'대학 1학년 때 미팅에서 만난 여자였어요.','pos_sentence':'대학__01/NNG 1/SN 학년/NNG 때__01/NNG 미팅/NNG 에서/JKB 만나/VV ᆫ/ETM 여자__02/NNG 이/VCP 었/EP 어요/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'<에델바이스>는 바로 이 영화에서 불린 노래이다.','pos_sentence':'</SS 에델바이스/NNP >/SS 는/JX 바로/MAG 이/MM 영화__01/NNG 에서/JKB 불리__04/VV ᆫ/ETM 노래/NNG __01/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'빛바랜 초겨울의 어스름이 아파트 마당에서 엉거주춤하고 있었다.','pos_sentence':'빛바래/VA ᆫ/ETM 초겨울/NNG 의/JKG 어스름/NNG 이/JKS 아파트/NNG 마당/NNG 에서/JKB 엉거주춤/MAG 하/XSV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'집에서 동화책을 보았습니다.','pos_sentence':'집__01/NNG 에서/JKB 동화책/NNG 을/JKO 보/VV 았/EP 습니다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'프랑스의 어느 국민학교에서 학년말 학예회가 열렸다.','pos_sentence':'프랑스/NNP 의/JKG 어느/MM 국민학교/NNG 에서/JKB 학년/NNG 말__11/NNB 학예회/NNG 가/JKS 열리__02/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'또 한 동창인 P는 약간 가난한 가정에서 자랐다.','pos_sentence':'또/MAJ 한/MM 동창__01/NNG 이/VCP ᆫ/ETM P/SL 는/JX 약간/MAG 가난__01/NNG 하/XSA ᆫ/ETM 가정__06/NNG 에서/JKB 자라__01/VV 았/EP 다/EF ./SF'}]}
,{'postposition':'eyse','function':'src','sentences':[{'name':'-에서 (-eyse)','sentence':'드디어 대장 새의 입에서 명령이 떨어졌습니다.','pos_sentence':'드디어/MAG 대장__04/NNG 새__03/NNG 의/JKG 입/NNG 에서/JKB 명령__01/NNG 이/JKS 떨어지/VV 었/EP 습니다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'바람이 서북쪽에서 불어오고 있었다.','pos_sentence':'바람__01/NNG 이/JKS 서북쪽/NNG 에서/JKB 불어오/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'개팔자가 상팔자라는 속담이 갑자기 그의 머릿속에서 튀어나왔다.','pos_sentence':'개__03/NNG 팔자__01/NNG 가/JKS 상팔자/NNG 이/VCP 라는/ETM 속담/NNG 이/JKS 갑자기/MAG 그/NP 의/JKG 머릿속/NNG 에서/JKB 튀어나오/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'동굴 안에서 대답 대신 몇발의 총성이 튀어나왔다.','pos_sentence':'동굴/NNG 안__01/NNG 에서/JKB 대답/NNG 대신__03/NNG 몇/MM 발__09/NNB 의/JKG 총성/NNG 이/JKS 튀어나오/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그 웃음이 숲 속에서 불어오는 바람처럼 상큼하기만 하다.','pos_sentence':'그/MM 웃음/NNG 이/JKS 숲__01/NNG 속__01/NNG 에서/JKB 불어오/VV 는/ETM 바람__01/NNG 처럼/JKB 상큼/XR 하/XSA 기/ETN 만/JX 하/VX 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'초소에서 조명탄이 다시 올랐다.','pos_sentence':'초소/NNG 에서/JKB 조명탄/NNG 이/JKS 다시/MAG 오르/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'여자의 입에서 아주 익숙한 한국말이 튀어나왔다.','pos_sentence':'여자__02/NNG 의/JKG 입/NNG 에서/JKB 아주/MAG 익숙/XR 하/XSA ᆫ/ETM 한국말/NNG 이/JKS 튀어나오/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'이러한 자연미의 결함에서 예술미의 필연성이 나온다.','pos_sentence':'이러/XR 하/XSA ᆫ/ETM 자연미/NNG 의/JKG 결함__01/NNG 에서/JKB 예술미/NNG 의/JKG 필연__01/NNG 성/XSN 이/JKS 나오/VV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'오혜정이 먼저 자리에서 일어섰다.','pos_sentence':'오혜정/NNP 이/JKS 먼저/MAG 자리__01/NNG 에서/JKB 일어서/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'가슴속에서 배신감 비슷한 감정이 울컥 치솟았다.','pos_sentence':'가슴속/NNG 에서/JKB 배신감/NNG 비슷/XR 하/XSA ᆫ/ETM 감정__06/NNG 이/JKS 울컥/MAG 치솟/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'가족들은 어둠과 함께 욕망의 전쟁터에서 돌아온다.','pos_sentence':'가족__01/NNG 들/XSN 은/JX 어둠/NNG 과/JKB 함께/MAG 욕망/NNG 의/JKG 전쟁터/NNG 에서/JKB 돌아오/VV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'옥점이는 책상 빼랍에서 초콜릿곽을 내놓았다.','pos_sentence':'옥점이/NNP 는/JX 책상__01/NNG 빼랍/NNG 에서/JKB 초콜릿/NNG 곽__02/NNG 을/JKO 내놓/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'다음 날은 시골에서 할아버지가 올라오셨습니다.','pos_sentence':'다음__01/NNG 날__01/NNG 은/JX 시골/NNG 에서/JKB 할아버지/NNG 가/JKS 올라오/VV 시/EP 었/EP 습니다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'청주 정신병원에서 전동 온 환자였다.','pos_sentence':'청주/NNP 정신__12/NNG 병원__02/NNG 에서/JKB 전동__88/NNG 오/VV ᆫ/ETM 환자__03/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'효철은 소파에서 상체를 일으켰다.','pos_sentence':'효철/NNP 은/JX 소파__06/NNG 에서/JKB 상체__01/NNG 를/JKO 일으키/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'나는 사무실에서 나왔다.','pos_sentence':'나/NP 는/JX 사무실/NNG 에서/JKB 나오/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'동경대학, 조도전대학 도서관에서 매일을 보냈다.','pos_sentence':'동경대학/NNP ,/SP 조도전대학/NNP 도서관/NNG 에서/JKB 매일/NNG 을/JKO 보내/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'이들이 지배계급 하층에서 분화되어 나온 계층이다.','pos_sentence':'이/NP 들/XSN 이/JKS 지배__01/NNG 계급__02/NNG 하층/NNG 에서/JKB 분화__01/NNG 되/XSV 어/EC 나오/VV ᆫ/ETM 계층/NNG 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그도 역시 부두에서 돌아오는 모양이다.','pos_sentence':'그/NP 도/JX 역시/MAG 부두__01/NNG 에서/JKB 돌아오/VV 는/ETM 모양__02/NNG 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그러나 배삼룡 분장의 하이라이트는 실수에서 나왔다.','pos_sentence':'그러나/MAJ 배삼룡/NNP 분장__05/NNG 의/JKG 하이라이트/NNG 는/JX 실수__01/NNG 에서/JKB 나오/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그들은 무슨 환경운동단체에서 왔다고 했다.','pos_sentence':'그/NP 들/XSN 은/JX 무슨/MM 환경__02/NNG 운동__02/NNG 단체__02/NNG 에서/JKB 오/VV 았/EP 다고/EC 하/VX 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그녀는 주머니에서 유인물 몇 장을 꺼내어주었다.','pos_sentence':'그녀/NP 는/JX 주머니/NNG 에서/JKB 유인물/NNG 몇/MM 장__22/NNB 을/JKO 꺼내/VV 어/EC 주/VX 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'물론 안내실 쪽에서 들려 오는 소리였다.','pos_sentence':'물론/MAG 안내실/NNG 쪽__05/NNB 에서/JKB 들리__03/VV 어/EC 오/VX 는/ETM 소리__01/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'학교에서 오는 길이었다.','pos_sentence':'학교/NNG 에서/JKB 오/VV 는/ETM 길__01/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그 소리는 절실함에서 우러나오는 것이었다.','pos_sentence':'그/MM 소리__01/NNG 는/JX 절실/XR 하/XSA ᄆ/ETN 에서/JKB 우러나오/VV 는/ETM 것/NNB 이/VCP 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'두번째 호출은 12층에서 왔다.','pos_sentence':'두/MM 번/NNB 째/XSN 호출/NNG 은/JX 12/SN 층__02/NNG 에서/JKB 오/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'남자는 생수통을 어깨에서 내려놓는다.','pos_sentence':'남자__02/NNG 는/JX 생수__02/NNG 통__10/NNG 을/JKO 어깨__01/NNG 에서/JKB 내려놓/VV 는다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'오반장은 자리에서 일어났다.','pos_sentence':'오/NNP 반장__08/NNG 은/JX 자리__01/NNG 에서/JKB 일어나/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그리고 불안증, 신경피로 등에서 오는 우울증도 해소시켜준다.','pos_sentence':'그리고/MAJ 불안증/NNG ,/SP 신경__04/NNG 피로__02/NNG 등__05/NNB 에서/JKB 오/VV 는/ETM 우울증/NNG 도/JX 해소__03/NNG 시키/XSV 어/EC 주/VX ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그것은 주로 어머니의 성격과 생활에서 오는 것이다.','pos_sentence':'그것/NP 은/JX 주로/MAG 어머니/NNG 의/JKG 성격__02/NNG 과/JC 생활/NNG 에서/JKB 오/VV 는/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'일정하다는 것은 과정 자체의 성질에서 온다.','pos_sentence':'일정__01/NNG 하/XSA 다는/ETM 것/NNB 은/JX 과정__03/NNG 자체__02/NNG 의/JKG 성질/NNG 에서/JKB 오/VV ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'순천시에서 낙안까지 시내버스가 있다.','pos_sentence':'순천시/NNP 에서/JKB 낙안/NNP 까지/JX 시내버스/NNG 가/JKS 있/VV 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'후에에서 하노이를 향하는 야간특급열차의 침대칸은 깨끗하다.','pos_sentence':'후에/NNP 에서/JKB 하노이/NNP 를/JKO 향하/VV 는/ETM 야간/NNG 특급__01/NNG 열차__02/NNG 의/JKG 침대칸/NNG 은/JX 깨끗/XR 하/XSA 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'제과점은 대로변에서 이십분쯤을 더 걸어가야 한다.','pos_sentence':'제과점/NNG 은/JX 대로변/NNG 에서/JKB 이십/NR 분__08/NNB 쯤/XSN 을/JKO 더/MAG 걸어가/VV 아야/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'굴비도 한자 이름에서 왔다.','pos_sentence':'굴비/NNG 도/JX 한자__02/NNG 이름/NNG 에서/JKB 오/VV 았/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그러므로 옛부터 가난 속에서 효자 나온다고 이야기하였던 것이다.','pos_sentence':'그러므로/MAJ 옛/NNG 부터/JX 가난__01/NNG 속__01/NNG 에서/JKB 효자__01/NNG 나오/VV ᆫ다고/EC 이야기/NNG 하/XSV 았/EP 던/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'그가 주머니에서 통장을 꺼냈다.','pos_sentence':'그/NP 가/JKS 주머니/NNG 에서/JKB 통장__02/NNG 을/JKO 꺼내/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'이와 같은 견해는 여러 철학자의 입장에서 피력되었다.','pos_sentence':'이/NP 와/JKB 같/VA 은/ETM 견해__02/NNG 는/JX 여러/MM 철학자/NNG 의/JKG 입장__04/NNG 에서/JKB 피력/NNG 되/XSV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'서울에서 C시까지는 한시간 반 가량이 걸렸다.','pos_sentence':'서울/NNP 에서/JKB C/SL 시__06/NNG 까지/JX 는/JX 한/MM 시간__04/NNG 반__07/NNG 가량__x06/NNG 이/JKS 걸리__01/VV 었/EP 다/EF ./SF'},
{'name':'-에서 (-eyse)','sentence':'응징은 너무 빨리 엉뚱한 곳에서 찾아왔다.','pos_sentence':'응징/NNG 은/JX 너무/MAG 빨리/MAG 엉뚱/XR 하/XSA ᆫ/ETM 곳__01/NNG 에서/JKB 찾아오/VV 았/EP 다/EF ./SF'}]}
,{'postposition':'lo','function':'crt','sentences':[{'name':'-으로 (-(u)lo)','sentence':'그러나 이것만으로는 아무 소용이 없다.','pos_sentence':'그러나/MAJ 이것/NP 만/JX 으로/JKB 는/JX 아무/MM 소용__07/NNG 이/JKS 없/VA 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'구체적으로는 기억이 안난다.','pos_sentence':'구체__02/NNG 적/XSN 으로/JKB 는/JX 기억/NNG 이/JKS 안/MAG 나/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'지구관측위성은 세번째로 비중이 높은 인공위성.','pos_sentence':'지구__04/NNG 관측/NNG 위성__06/NNG 은/JX 세/MM 번/NNB 째/XSN 로/JKB 비중/NNG 이/JKS 높/VA 은/ETM 인공위성/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그것이 대학 노트로 다섯 권이나 되었다.','pos_sentence':'그것/NP 이/JKS 대학__01/NNG 노트/NNG 로/JKB 다섯/NR 권/NNB 이나/JX 되__01/VV 었/EP 다/EC'},
{'name':'-으로 (-(u)lo)','sentence':'특히 한강 이남지역이 15%대로 가장 높았다.','pos_sentence':'특히/MAG 한강/NNP 이남__02/NNG 지역__03/NNG 이/JKS 5/SN %/SW 대/XSN 로/JKB 가장__01/MAG 높/VA 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'축사에는 면장이 첫번으로 올라갔다.','pos_sentence':'축사__04/NNG 에/JKB 는/JX 면장__02/NNG 이/JKS 첫/MM 번/NNB 으로/JKB 올라가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그러나 실제로는 다시 몇 가지로 세분할 수 있다.','pos_sentence':'그러나/MAJ 실제로/MAG 는/JX 다시/MAG 몇/MM 가지/NNB 로/JKB 세분__03/NNG 하/XSV ᆯ/ETM 수__02/NNB 있/VV 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'한 시간 연습이 두 시간, 세 시간으로 늘어났다.','pos_sentence':'한/MM 시간__04/NNG 연습__03/NNG 이/JKS 두/MM 시간__04/NNG ,/SP 세/MM 시간__04/NNG 으로/JKB 늘어나/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'한편 일본의 경우는 지방 단위로 이루어진다.','pos_sentence':'한편/NNG 일본/NNP 의/JKG 경우__03/NNG 는/JX 지방__05/NNG 단위__02/NNG 로/JKB 이루어지/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그는 78세의 나이로 열반에 들었다.','pos_sentence':'그/NP 는/JX 78/SN 세/NNB 의/JKG 나이__01/NNG 로/JKB 열반/NNG 에/JKB 들__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그가 세 번째로 속삭였다.','pos_sentence':'그/NP 가/JKS 세/MM 번/NNB 째/XSN 로/JKB 속삭이/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이것은 몇 가지로 생각해 볼 수 있다.','pos_sentence':'이것/NP 은/JX 몇/MM 가지/NNB 로/JKB 생각__01/NNG 하/XSV 아/EC 보/VX ᆯ/ETM 수__02/NNB 있/VV 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'벌써 몇 번째로 하는 작업이었다.','pos_sentence':'벌써/MAG 몇/MM 번/NNB 째/XSN 로/JKB 하/VV 는/ETM 작업__01/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'서울에서의 초연 마지막 날이 내일로 다가왔다.','pos_sentence':'서울/NNP 에서/JKB 의/JKG 초연__02/NNG 마지막/NNG 날__01/NNG 이/JKS 내일/NNG 로/JKB 다가오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그래서 진상조사단 구성 인원도 근 스무명으로 엮었지요.','pos_sentence':'그래서/MAJ 진상__03/NNG 조사단/NNG 구성__07/NNG 인원/NNG 도/JX 근/MM 스무/MM 명/NNB 으로/JKB 엮/VV 었/EP 지요/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이 어린이 마음의 속성을 저는 세 가지로 봅니다.','pos_sentence':'이/MM 어린이/NNG 마음__01/NNG 의/JKG 속성__05/NNG 을/JKO 저/NP 는/JX 세/MM 가지/NNB 로/JKB 보__01/VV ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 중에서도 추석이 첫째 손가락으로 꼽힌다.','pos_sentence':'그/MM 중__04/NNB 에서/JKB 도/JX 추석__01/NNG 이/JKS 첫째/NR 손가락/NNG 으로/JKB 꼽히__01/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'경기 수로는 꼭 10경기 만에 터졌다.','pos_sentence':'경기__11/NNG 수__26/NNG 로/JKB 는/JX 꼭__03/MAG 10/SN 경기__11/NNG 만__01/NNB 에/JKB 터지/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'수술은 예상 이상의 단시간으로 끝났다.','pos_sentence':'수술__05/NNG 은/JX 예상__02/NNG 이상__05/NNG 의/JKG 단시간/NNG 으로/JKB 끝나/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'도매가로 판매하므로 시중보다 10% 정도 싸다.','pos_sentence':'도매가/NNG 로/JKB 판매/NNG 하/XSV 므로/EC 시중__03/NNG 보다/JKB 10/SN %/SW 정도__11/NNG 싸__05/VA 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'등장인물은 크게 세 유형으로 분류된다.','pos_sentence':'등장인물/NNG 은/JX 크/VA 게/EC 세/MM 유형__07/NNG 으로/JKB 분류__03/NNG 되/XSV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'생산액으로 따지면 제조업 중 8.7퍼센트,','pos_sentence':'생산액/NNG 으로/JKB 따지__01/VV 면/EC 제조업/NNG 중__04/NNB 8/SN ./SF 7/SN 퍼센트/NNG ,/SP'},
{'name':'-으로 (-(u)lo)','sentence':'1989 년에는 18%로 늘어났다.','pos_sentence':'1989/SN 년__02/NNB 에/JKB 는/JX 18/SN %/SW 로/JKB 늘어나/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'기준) 만에 하락세로 돌아섰다.','pos_sentence':'기준/NNG )/SS 만__01/NNB 에/JKB 하락세/NNG 로/JKB 돌아서/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이 책은 3부로 이루어져 있다.','pos_sentence':'이/MM 책__01/NNG 은/JX 3/SN 부/NNB 로/JKB 이루__01/VV 어/EC 지/VX 어/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'한 마리씩 용도별로 따로 썰어 각각 보관한다.','pos_sentence':'한/MM 마리/NNB 씩/XSN 용도__02/NNG 별/XSN 로/JKB 따로/MAG 썰__01/VV 어/EC 각각/MAG 보관__01/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'일기를 여러 방법으로 써 본다.','pos_sentence':'일기__12/NNG 를/JKO 여러/MM 방법/NNG 으로/JKB 쓰/VV 어/EC 보/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'옹기는 질그릇과 오지그릇 둘로 나눈다.','pos_sentence':'옹기__02/NNG 는/JX 질그릇/NNG 과/JC 오지그릇/NNG 둘/NR 로/JKB 나누/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그것을 첫번째로 묻고 싶습니다.','pos_sentence':'그것/NP 을/JKO 첫/MM 번/NNB 째/XSN 로/JKB 묻__03/VV 고/EC 싶/VX 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'사람은 두 가지로 성장할 수 있다.','pos_sentence':'사람/NNG 은/JX 두/MM 가지/NNB 로/JKB 성장__01/NNG 하/XSV ᆯ/ETM 수__02/NNB 있/VV 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'세로 15 cm로 정해져 있다.','pos_sentence':'세로__01/NNG 15/SN cm/SL 로/JKB 정하/VV 아/EC 지/VX 어/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'생식은 무성 생식과 유성 생식으로 나뉜다.','pos_sentence':'생식/NNG 은/JX 무성__02/NNG 생식/NNG 과/JC 유성__01/NNG 생식/NNG 으로/JKB 나뉘/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'다리는 4cm 길이로 썬다.','pos_sentence':'다리__01/NNG 는/JX 4/SN cm/SW 길이/NNG 로/JKB 썰__01/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이 명제에 대해서는 두 가지로 논증합니다.','pos_sentence':'이/MM 명제/NNG 에/JKB 대하__02/VV 아서/EC 는/JX 두/MM 가지/NNB 로/JKB 논증__02/NNG 하/XSV ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'30년대의 형성기, 그리고 40년대의 방황기로 나뉜다.','pos_sentence':'30/SN 년대/NNB 의/JKG 형성기/NNG ,/SP 그리고/MAJ 40/SN 년대/NNB 의/JKG 방황기/NNG 로/JKB 나뉘/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'지금의 국기는 다시 3개로 돌아왔다.','pos_sentence':'지금__03/NNG 의/JKG 국기__07/NNG 는/JX 다시/MAG 3/SN 개/NNB 로/JKB 돌아오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'삼성과 기아는 일찌감치 올 시즌 2강으로 꼽혔다.','pos_sentence':'삼성/NNP 과/JC 기아/NNP 는/JX 일찌감치/MAG 올/MM 시즌/NNG 2/SN 강__88/NNG 으로/JKB 꼽히__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'2개월 말경에 수정란은 4cm 정도로 커진다.','pos_sentence':'2/SN 개월/NNB 말__11/NNB 경/XSN 에/JKB 수정란/NNG 은/JX 4/SN cm/SL 정도__11/NNG 로/JKB 커지/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'병석이가 두 번째로 정학을 맞은 것이다.','pos_sentence':'병석이/NNP 가/JKS 두/MM 번/NNB 째/XSN 로/JKB 정학__04/NNG 을/JKO 맞__02/VV 은/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'쿠웨이트와 인도도 1-1로 비겼다.','pos_sentence':'쿠웨이트/NNP 와/JC 인도/NNP 도/JX 1/SN -/SS 1/SN 로/JKB 비기__01/VV 었/EP 다/EF ./SF'}]}
,{'postposition':'lo','function':'dir','sentences':[{'name':'-으로 (-(u)lo)','sentence':'쇠전꾼들이 술청으로 돌아왔다.','pos_sentence':'쇠전__01/NNG 꾼/XSN 들/XSN 이/JKS 술청/NNG 으로/JKB 돌아오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그녀의 오른발이 위로 치솟았다.','pos_sentence':'그녀/NP 의/JKG 오른발/NNG 이/JKS 위__01/NNG 로/JKB 치솟/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'두 사람이 동시에 밖으로 튀어나왔다.','pos_sentence':'두/MM 사람/NNG 이/JKS 동시__02/NNG 에/JKB 밖/NNG 으로/JKB 튀어나오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'일제히 수십 개의 화살이 하늘로 날아올랐다.','pos_sentence':'일제히/MAG 수십/NR 개/NNB 의/JKG 화살__01/NNG 이/JKS 하늘/NNG 로/JKB 날아오르/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'노인 한 사람이 주저주저 앞으로 나왔다.','pos_sentence':'노인__01/NNG 한/MM 사람/NNG 이/JKS 주저주저/MAG 앞/NNG 으로/JKB 나오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 방문 앞으로 두 놈이 다가들었다.','pos_sentence':'그/MM 방문__02/NNG 앞/NNG 으로/JKB 두/MM 놈/NNB 이/JKS 다가들/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'사람들의 눈길이 이 쪽으로 쏠렸다.','pos_sentence':'사람/NNG 들/XSN 의/JKG 눈길__01/NNG 이/JKS 이/MM 쪽__05/NNB 으로/JKB 쏠리/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'달이 어느새 서쪽으로 기울고 있었습니다.','pos_sentence':'달__05/NNG 이/JKS 어느새/MAG 서쪽/NNG 으로/JKB 기울/VV 고/EC 있/VX 었/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아이의 턱이 다시 무릎 위로 떨어졌다.','pos_sentence':'아이__01/NNG 의/JKG 턱__01/NNG 이/JKS 다시/MAG 무릎/NNG 위__01/NNG 로/JKB 떨어지/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'해숙이 구석 쪽으로 얼굴을 돌렸다.','pos_sentence':'해숙/NNP 이/JKS 구석__01/NNG 쪽__05/NNB 으로/JKB 얼굴/NNG 을/JKO 돌리__04/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'사람들의 시선이 일제히 그 쪽으로 쏠렸다.','pos_sentence':'사람/NNG 들/XSN 의/JKG 시선__03/NNG 이/JKS 일제히/MAG 그/MM 쪽__05/NNB 으로/JKB 쏠리/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그곳에서 왼쪽으로 약사봉 능선이 나 있었다.','pos_sentence':'그곳/NP 에서/JKB 왼쪽/NNG 으로/JKB 약사봉/NNP 능선__01/NNG 이/JKS 나/VV 아/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'박선생이 수업을 중단하고 복도로 나왔다.','pos_sentence':'박/NNP 선생__01/NNG 이/JKS 수업__04/NNG 을/JKO 중단__04/NNG 하/XSV 고/EC 복도__04/NNG 로/JKB 나오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'벽장 속의 옷들이 모조리 밖으로 나와 있다.','pos_sentence':'벽장__02/NNG 속__01/NNG 의/JKG 옷/NNG 들/XSN 이/JKS 모조리/MAG 밖/NNG 으로/JKB 나오/VV 아/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'어쩐지 발걸음이 집으로 향해지지 않았습니다.','pos_sentence':'어쩐지/MAG 발걸음/NNG 이/JKS 집__01/NNG 으로/JKB 향하/VV 아/EC 지/VX 지/EC 않/VX 았/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'공양주보살이 거처하는 방으로 갔다.','pos_sentence':'공양주/NNG 보살__02/NNG 이/JKS 거처__02/NNG 하/XSV 는/ETM 방__07/NNG 으로/JKB 가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'두 사람의 시선이 함께 야자나무로 쏠렸다.','pos_sentence':'두/MM 사람/NNG 의/JKG 시선__03/NNG 이/JKS 함께/MAG 야자나무/NNG 로/JKB 쏠리/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'빗물이 입속으로 스며든다.','pos_sentence':'빗물/NNG 이/JKS 입속/NNG 으로/JKB 스며들/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'바스락 소리에도 눈길이 자꾸 문 쪽으로 간다.','pos_sentence':'바스락/MAG 소리__01/NNG 에/JKB 도/JX 눈길__01/NNG 이/JKS 자꾸/MAG 문__05/NNG 쪽__05/NNB 으로/JKB 가/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'나는 터미널 쪽으로 서둘러 간다.','pos_sentence':'나/NP 는/JX 터미널/NNG 쪽__05/NNB 으로/JKB 서두르/VV 어/EC 가/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'훈아는 작은방 앞으로 달려갔다.','pos_sentence':'훈아/NNP 는/JX 작은방/NNG 앞/NNG 으로/JKB 달려가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'영달이가 대합실 바깥으로 나가며 말했다.','pos_sentence':'영달이/NNP 가/JKS 대합실/NNG 바깥/NNG 으로/JKB 나가/VV 며/EC 말__01/NNG 하/XSV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'우리 여섯 명은 동대문 시장 헌 책방 골목으로 갔다.','pos_sentence':'우리/NP 여섯/NR 명/NNB 은/JX 동대문/NNP 시장__04/NNG 헌/MM 책방__01/NNG 골목__01/NNG 으로/JKB 가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그녀의 한쪽 다리가 다른쪽 다리 위로 올라갔다.','pos_sentence':'그녀/NP 의/JKG 한쪽/NNG 다리__01/NNG 가/JKS 다른/MM 쪽__05/NNB 다리__01/NNG 위__01/NNG 로/JKB 올라가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'영구는 혼자 가만히 외양간으로 나갔다.','pos_sentence':'영구/NNP 는/JX 혼자__01/NNG 가만히/MAG 외양간/NNG 으로/JKB 나가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'다음날 의식을 회복한 나 역시 경찰서로 끌려갔다.','pos_sentence':'다음날/NNG 의식__03/NNG 을/JKO 회복/NNG 하/XSV ᆫ/ETM 나/NP 역시/MAG 경찰서/NNG 로/JKB 끌려가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'야삽이 엉덩이로 날아왔다.','pos_sentence':'야삽/NNG 이/JKS 엉덩이/NNG 로/JKB 날아오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그리고 천천히 미끄럼틀 위로 올라갔어.','pos_sentence':'그리고/MAJ 천천히/MAG 미끄럼틀/NNG 위__01/NNG 로/JKB 올라가/VV 았/EP 어/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'모두 물줄기로 뛰어들었다.','pos_sentence':'모두/MAG 물줄기/NNG 로/JKB 뛰어들/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'눈길을 탁자 위로 떨어뜨렸다.','pos_sentence':'눈길__01/NNG 을/JKO 탁자__01/NNG 위__01/NNG 로/JKB 떨어뜨리/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'사람들은 대한극장 쪽으로 정신없이 뛰어나갔다.','pos_sentence':'사람/NNG 들/XSN 은/JX 대한극장/NNP 쪽__05/NNB 으로/JKB 정신없이/MAG 뛰어나가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'금복이는 아이들한테로 힘껏 달려갔습니다.','pos_sentence':'금복이/NNP 는/JX 아이__01/NNG 들/XSN 한테/JKB 로/JKB 힘껏/MAG 달려가/VV 았/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'둘째날 아침, 일찌감치 강의실로 갔다.','pos_sentence':'둘째/NR 날__01/NNG 아침/NNG ,/SP 일찌감치/MAG 강의실/NNG 로/JKB 가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'모든 사람의 시선이 그의 얼굴로 날아들었다.','pos_sentence':'모든/MM 사람/NNG 의/JKG 시선__03/NNG 이/JKS 그/NP 의/JKG 얼굴/NNG 로/JKB 날아들/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'효선씨가 LA로 유학을 떠난 것이다.','pos_sentence':'효선/NNP 씨/NNB 가/JKS LA/SL 로/JKB 유학__04/NNG 을/JKO 떠나/VV ᆫ/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'농협 창고 옆골목으로 들어갔다.','pos_sentence':'농협/NNP 창고__01/NNG 옆/NNG 골목__01/NNG 으로/JKB 들어가__01/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그리고 사체가 발견된 곳으로 옮겨졌다.','pos_sentence':'그리고/MAJ 사체__06/NNG 가/JKS 발견__01/NNG 되/XSV ᆫ/ETM 곳__01/NNG 으로/JKB 옮기/VV 어/EC 지/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아낙은 다시 힘없이 짚단 위로 나자빠졌다.','pos_sentence':'아낙/NNG 은/JX 다시/MAG 힘없이/MAG 짚단/NNG 위__01/NNG 로/JKB 나자빠지/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'창호의 경운기는 샛개 농장으로 갔다.','pos_sentence':'창호/NNP 의/JKG 경운기/NNG 는/JX 샛개/NNP 농장__05/NNG 으로/JKB 가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'기획 2부는 급히 일본의 자동차도서관으로 갔다.','pos_sentence':'기획__01/NNG 2/SN 부__15/NNB 는/JX 급히/MAG 일본/NNP 의/JKG 자동차/NNG 도서관/NNG 으로/JKB 가/VV 았/EP 다/EF ./SF'}]}
,{'postposition':'lo','function':'eff','sentences':[{'name':'-으로 (-(u)lo)','sentence':'그리고 그 결과로 오줌이 나온다.','pos_sentence':'그리고/MAJ 그/MM 결과__02/NNG 로/JKB 오줌/NNG 이/JKS 나오/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'온몸이 땀으로 흠뻑 젖어 있었다.','pos_sentence':'온몸/NNG 이/JKS 땀__01/NNG 으로/JKB 흠뻑/MAG 젖__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'오랜 장마로 냇물이며 강물들이 출렁출렁 넘쳐흐른다.','pos_sentence':'오랜/MM 장마__01/NNG 로/JKB 냇물/NNG 이/VCP 며/EC 강물/NNG 들/XSN 이/JKS 출렁출렁/MAG 넘쳐흐르/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'고속도로변이 쓰레기로 몸살을 앓고 있다.','pos_sentence':'고속도로/NNG 변__09/NNG 이/JKS 쓰레기/NNG 로/JKB 몸살__01/NNG 을/JKO 앓/VV 고/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'거리는 오토바이와 자동차들 그리고 인파로 정신이 없다.','pos_sentence':'거리__01/NNG 는/JX 오토바이/NNG 와/JC 자동차/NNG 들/XSN 그리고/MAJ 인파/NNG 로/JKB 정신__12/NNG 이/JKS 없/VA 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'피서객들로 전국이 붐비는 8월.','pos_sentence':'피서객/NNG 들/XSN 로/JKB 전국__03/NNG 이/JKS 붐비/VV 는/ETM 8/SN 월/NNB ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'온몸이 땀으로 후줄근하게 젖어 있었다.','pos_sentence':'온몸/NNG 이/JKS 땀__01/NNG 으로/JKB 후줄근/XR 하/XSA 게/EC 젖__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'돌연한 슬픔으로 목이 메었다.','pos_sentence':'돌연/MAG 하/XSA ᆫ/ETM 슬픔/NNG 으로/JKB 목__01/NNG 이/JKS 메__02/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'계속되는 불행으로 마을이 온통 쑥밭이 되었다.','pos_sentence':'계속__04/NNG 되/XSV 는/ETM 불행/NNG 으로/JKB 마을__01/NNG 이/JKS 온통/MAG 쑥밭/NNG 이/JKC 되__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'연속 실책성 플레이로 천보성감독의 속을 태운다.','pos_sentence':'연속__02/NNG 실책/NNG 성/XSN 플레이/NNG 로/JKB 천보성/NNP 감독__02/NNG 의/JKG 속__01/NNG 을/JKO 태우__01/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 덕택으로 우리는 나라를 되찾은 것입니다.','pos_sentence':'그/MM 덕택/NNG 으로/JKB 우리/NP 는/JX 나라/NNG 를/JKO 되찾/VV 은/ETM 것/NNB 이/VCP ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'따라서 칼슘 방출의 증가로 골다공증의 현상이 일어난다.','pos_sentence':'따라서/MAJ 칼슘/NNG 방출__01/NNG 의/JKG 증가__01/NNG 로/JKB 골다공증/NNG 의/JKG 현상__04/NNG 이/JKS 일어나/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'하늘을 가린 먹구름으로 사방이 어둑하다.','pos_sentence':'하늘/NNG 을/JKO 가리__02/VV ᆫ/ETM 먹구름/NNG 으로/JKB 사방__03/NNG 이/JKS 어둑/XR 하/XSA 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'고문 후유증으로 건구역질, 불안, 우울증에 시달렸다.','pos_sentence':'고문__04/NNG 후유증/NNG 으로/JKB 건구역__05/NNG 질/XSN ,/SP 불안__01/NNG ,/SP 우울증/NNG 에/JKB 시달리/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'웨이크필드는 이날 경기 초반 제구력 난조로 어려움을 겪었다.','pos_sentence':'웨이크필드/NNP 는/JX 이날/NNG 경기__11/NNG 초반__01/NNG 제구력/NNG 난조__01/NNG 로/JKB 어려움/NNG 을/JKO 겪/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'가슴속이 온통 분노로 소용돌이쳤기 때문이었다.','pos_sentence':'가슴속/NNG 이/JKS 온통/MAG 분노/NNG 로/JKB 소용돌이치/VV 었/EP 기/ETN 때문/NNB 이/VCP 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'수치와 분노로 그녀는 부르르 몸을 떨었다.','pos_sentence':'수치__03/NNG 와/JC 분노/NNG 로/JKB 그녀/NP 는/JX 부르르/MAG 몸__01/NNG 을/JKO 떨__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'정치권이 신당 이야기로 어지럽다.','pos_sentence':'정치__03/NNG 권/XSN 이/JKS 신/XPN 당__14/NNG 이야기/NNG 로/JKB 어지럽/VA 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'폭격으로 잿더미가 된 마을이었습니다.','pos_sentence':'폭격/NNG 으로/JKB 잿더미/NNG 가/JKC 되__01/VV ᆫ/ETM 마을__01/NNG 이/VCP 었/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'지난해 집중호우로 엉망이 됐던 용인 가족묘지.','pos_sentence':'지난해/NNG 집중__02/NNG 호우__05/NNG 로/JKB 엉망/NNG 이/JKC 되__01/VV 었/EP 던/ETM 용인/NNP 가족__01/NNG 묘지__02/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'말하는 이빨 사이와 혓바닥도 탄가루로 새까맸다.','pos_sentence':'말__01/NNG 하/XSV 는/ETM 이빨/NNG 사이__01/NNG 와/JC 혓바닥/NNG 도/JX 탄가루/NNG 로/JKB 새까맣/VA 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아이들은 너나없이 땀으로 물쥐처럼 젖어 있었다.','pos_sentence':'아이__01/NNG 들/XSN 은/JX 너나없이/MAG 땀__01/NNG 으로/JKB 물쥐/NNG 처럼/JKB 젖__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'6·25전쟁으로 집안이 풍비박산이 되었다.','pos_sentence':'6/SN ·/SP 25/SN 전쟁/NNG 으로/JKB 집안__01/NNG 이/JKS 풍비박산/NNG 이/JKC 되__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'어머니의 얼굴은 눈물로 흠뻑 젖어 있었다.','pos_sentence':'어머니/NNG 의/JKG 얼굴/NNG 은/JX 눈물__01/NNG 로/JKB 흠뻑/MAG 젖__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그의 얼굴은 괴로움과 분노로 일그러졌다.','pos_sentence':'그/NP 의/JKG 얼굴/NNG 은/JX 괴로움/NNG 과/JC 분노/NNG 로/JKB 일그러지/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'과로로 쓰러진 소녀 가장이었지.','pos_sentence':'과로__01/NNG 로/JKB 쓰러지/VV ᆫ/ETM 소녀__02/NNG 가장__07/NNG 이/VCP 었/EP 지/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'불볕 더위로 대구는 푹푹 찌고 있었다.','pos_sentence':'불볕/NNG 더위/NNG 로/JKB 대구/NNP 는/JX 푹푹/MAG 찌__05/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이번 사건으로 검찰과 경찰은 위신을 잃었다.','pos_sentence':'이번__01/NNG 사건__01/NNG 으로/JKB 검찰__02/NNG 과/JC 경찰__04/NNG 은/JX 위신__04/NNG 을/JKO 잃/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'제임스의 노력으로 제판은 승리의 조짐이 보였다.','pos_sentence':'제임스/NNP 의/JKG 노력__01/NNG 으로/JKB 재판__06/NNG 은/JX 승리/NNG 의/JKG 조짐/NNG 이/JKS 보이__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'큰바람의 호소로 강당은 눈물 바다를 이루었다.','pos_sentence':'큰바람/NNG 의/JKG 호소__01/NNG 로/JKB 강당/NNG 은/JX 눈물__01/NNG 바다/NNG 를/JKO 이루__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그리고 그로 인해서 좌절하게 된다.','pos_sentence':'그리고/MAJ 그/NP 로/JKB 인하/VV 아서/EC 좌절/NNG 하/XSV 게/EC 되/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그는 폐결핵으로 죽었다.','pos_sentence':'그/NP 는/JX 폐결핵/NNG 으로/JKB 죽__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'울진은 지금 시민들의 반대 열기로 뜨겁다.','pos_sentence':'울진/NNP 은/JX 지금__03/MAG 시민/NNG 들/XSN 의/JKG 반대__03/NNG 열기__07/NNG 로/JKB 뜨겁/VA 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'수많은 생각들로 머리 속은 혼란스러웠다.','pos_sentence':'수많/VA 은/ETM 생각__01/NNG 들/XSN 로/JKB 머리__01/NNG 속__01/NNG 은/JX 혼란/NNG 스럽/XSA 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'최첨단 기술 도입으로 선망의 대상이 되었던 프로젝트.','pos_sentence':'최/XPN 첨단__01/NNG 기술__01/NNG 도입/NNG 으로/JKB 선망__04/NNG 의/JKG 대상__11/NNG 이/JKC 되__01/VV 었/EP 던/ETM 프로젝트/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'정숙이의 가출로 학교는 술렁거렸다.','pos_sentence':'정숙이/NNP 의/JKG 가출__02/NNG 로/JKB 학교/NNG 는/JX 술렁거리/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'구영국민학교도 아파트 신축으로 갑자기 학교규모가 커졌다.','pos_sentence':'구영국민학교/NNP 도/JX 아파트/NNG 신축__03/NNG 으로/JKB 갑자기/MAG 학교/NNG 규모/NNG 가/JKS 커지/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'괴혈병 비타민 C의 결핍으로 일어나는 병.','pos_sentence':'괴혈병/NNG 비타민/NNG C/SL 의/JKG 결핍/NNG 으로/JKB 일어나/VV 는/ETM 병__04/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'국제 공항은 온통 기쁨으로 출렁거리고 있었습니다.','pos_sentence':'국제__02/NNG 공항__02/NNG 은/JX 온통/MAG 기쁨/NNG 으로/JKB 출렁거리/VV 고/EC 있/VX 었/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'도이미나의 친어머니는 오래 전에 자궁암으로 죽었다.','pos_sentence':'도이미나/NNP 의/JKG 친/XPN 어머니/NNG 는/JX 오래/MAG 전__08/NNG 에/JKB 자궁암/NNG 으로/JKB 죽__01/VV 었/EP 다/EF ./SF'}]}
,{'postposition':'lo','function':'fns','sentences':[{'name':'-으로 (-(u)lo)','sentence':'멍멍한 채로 시간이 흘러갔다.','pos_sentence':'멍멍/XR 하/XSA ᆫ/ETM 채__09/NNB 로/JKB 시간__04/NNG 이/JKS 흘러가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아내의 얼굴이 절망적으로 굳어지고 있었다.','pos_sentence':'아내__01/NNG 의/JKG 얼굴/NNG 이/JKS 절망__02/NNG 적/XSN 으로/JKB 굳어지/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'둘이 말없이 그런 상태로 한참 동안 앉아 있었다.','pos_sentence':'둘/NR 이/JKS 말없이/MAG 그런/MM 상태__01/NNG 로/JKB 한참/NNG 동안__01/NNG 앉/VV 아/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'인간이 갑작스레 앙골라 토끼로 변했기 때문은 아니다.','pos_sentence':'인간__01/NNG 이/JKS 갑작스레/MAG 앙골라/NNP 토끼/NNG 로/JKB 변하/VV 았/EP 기/ETN 때문/NNB 은/JX 아니/VCN 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'정직한 계산과 믿음이 당신을 스타로 만듭니다.','pos_sentence':'정직__01/NNG 하/XSA ᆫ/ETM 계산__01/NNG 과/JC 믿음/NNG 이/JKS 당신/NP 을/JKO 스타/NNG 로/JKB 만들/VV ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그런 합의와 합심이 저들을 강국으로 만들었다.','pos_sentence':'그런/MM 합의__01/NNG 와/JC 합심/NNG 이/JKS 저/NP 들/XSN 을/JKO 강국__01/NNG 으로/JKB 만들/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'명장(名將)이 전쟁을 승리로 이끈다.','pos_sentence':'명장__02/NNG (/SS 名將/SH )/SS 이/JKS 전쟁/NNG 을/JKO 승리/NNG 로/JKB 이끌/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'안정환이 선발로 나왔는데?','pos_sentence':'안정환/NNP 이/JKS 선발__03/NNG 로/JKB 나오/VV 았/EP 는데/EF ?/SF'},
{'name':'-으로 (-(u)lo)','sentence':'내가 악덕 기업주로 소문이 나 있다고?','pos_sentence':'내/NP 가/JKS 악덕/NNG 기업주/NNG 로/JKB 소문__02/NNG 이/JKS 나/VV 아/EC 있/VX 다고/EF ?/SF'},
{'name':'-으로 (-(u)lo)','sentence':'죽음이 그들을 예술가로 만든다.','pos_sentence':'죽음__01/NNG 이/JKS 그/NP 들/XSN 을/JKO 예술가/NNG 로/JKB 만들/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'자신이 벌레로 변해버렸다는 느낌.','pos_sentence':'자신__01/NNG 이/JKS 벌레__01/NNG 로/JKB 변하/VV 아/EC 버리/VX 었/EP 다는/ETM 느낌/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이유6 퀼트 노루발이 옵션으로 만들어 져 있다.','pos_sentence':'이유__04/NNG 6/SN 퀼트/NNG 노루발__01/NNG 이/JKS 옵션/NNG 으로/JKB 만들/VV 어/EC 지/VX 어/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이는 합성되어 백색의 덩어리로 보인다.','pos_sentence':'이/NP 는/JX 합성/NNG 되/XSV 어/EC 백색/NNG 의/JKG 덩어리/NNG 로/JKB 보이__01/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'냉장고, 텔레비전 따위를 싸구려로 팔았다.','pos_sentence':'냉장고/NNG ,/SP 텔레비전/NNG 따위/NNB 를/JKO 싸구려/NNG 로/JKB 팔/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아리스토텔레스 : 물고기나 새나 개구리의 형상으로 바뀌는군요.','pos_sentence':'아리스토텔레스/NNP :/SP 물고기/NNG 나/JC 새__03/NNG 나/JC 개구리/NNG 의/JKG 형상__04/NNG 으로/JKB 바뀌/VV 는군요/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 이유는 아직도 학계의 신비로 남아 있다.','pos_sentence':'그/MM 이유__04/NNG 는/JX 아직/MAG 도/JX 학계/NNG 의/JKG 신비__02/NNG 로/JKB 남/VV 아/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'식사 때 텔레비전을 주로 화제로 삼는 아이.','pos_sentence':'식사__03/NNG 때__01/NNG 텔레비전/NNG 을/JKO 주로/MAG 화제__07/NNG 로/JKB 삼__02/VV 는/ETM 아이__01/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'반대편 다리도 같은 방식으로 운동시킨다.','pos_sentence':'반대편/NNG 다리__01/NNG 도/JX 같/VA 은/ETM 방식__01/NNG 으로/JKB 운동__02/NNG 시키/XSV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'백만학도가 창환이를 열사로 떠받들었죠.','pos_sentence':'백만/NR 학도__01/NNG 가/JKS 창환이/NNP 를/JKO 열사__01/NNG 로/JKB 떠받들/VV 었/EP 죠/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'이것이 지금 전세계를 파멸로 몰아가고 있다.','pos_sentence':'이것/NP 이/JKS 지금__03/MAG 전__07/MM 세계__02/NNG 를/JKO 파멸/NNG 로/JKB 몰아가/VV 고/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'두 사람은 완벽한 커플로 보였다.','pos_sentence':'두/MM 사람/NNG 은/JX 완벽__01/NNG 하/XSA ᆫ/ETM 커플/NNG 로/JKB 보이__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'나는 종이공예 전문가로 널리 알려져 있다.','pos_sentence':'나/NP 는/JX 종이__01/NNG 공예__01/NNG 전문가/NNG 로/JKB 널리/MAG 알리/VV 어/EC 지/VX 어/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'혁진과 예리는 다시 서먹서먹한 관계로 돌아갔다.','pos_sentence':'혁진/NNP 과/JC 예리/NNP 는/JX 다시/MAG 서먹서먹/XR 하/XSA ᆫ/ETM 관계__05/NNG 로/JKB 돌아가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'로마인들은 조약을 신성한 것으로 여겼다.','pos_sentence':'로마인/NNG 들/XSN 은/JX 조약__01/NNG 을/JKO 신성__04/NNG 하/XSA ᆫ/ETM 것/NNB 으로/JKB 여기/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그는 30세 무렵 성균관 유생으로 있었다.','pos_sentence':'그/NP 는/JX 30/SN 세__13/NNB 무렵/NNB 성균관/NNP 유생__05/NNG 으로/JKB 있/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'보통 우승자는 무명베 1필을 상품으로 받았다.','pos_sentence':'보통/MAG 우승자/NNG 는/JX 무명베/NNG 1/SN 필__02/NNB 을/JKO 상품__04/NNG 으로/JKB 받__01/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그녀는 미륵산을 남편으로 대하고 있는 것이다.','pos_sentence':'그녀/NP 는/JX 미륵산/NNP 을/JKO 남편__01/NNG 으로/JKB 대하__02/VV 고/EC 있/VX 는/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'일곱시간을 내리 입석으로 갔다.','pos_sentence':'일곱/NR 시간__04/NNG 을/JKO 내리/MAG 입석__02/NNG 으로/JKB 가/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'김치나 장항아리를 술독으로 사용할 수는 없지요.','pos_sentence':'김치/NNG 나/JC 장항아리/NNG 를/JKO 술독__01/NNG 으로/JKB 사용__04/NNG 하/XSV ᆯ/ETM 수__02/NNB 는/JX 없/VA 지요/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'냉동인간으로 화석화 되는 겁니다.','pos_sentence':'냉동/NNG 인간__01/NNG 으로/JKB 화석__01/NNG 화/XSN 되__01/VV 는/ETM 것/NNB 이/VCP ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'탁구가 취미로 아마추어 수준을 넘는다.','pos_sentence':'탁구/NNG 가/JKS 취미__04/NNG 로/JKB 아마추어__01/NNG 수준/NNG 을/JKO 넘__01/VV 는다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'샐러드 재료로 웨스턴 오믈렛을 만들기 시작했다.','pos_sentence':'샐러드/NNG 재료__01/NNG 로/JKB 웨스턴/NNP 오믈렛/NNG 을/JKO 만들/VV 기/ETN 시작__01/NNG 하/XSV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'답답도 하실테니 심심풀이로 한 번 보시지요?','pos_sentence':'답답/XR 도/JX 하/VX 시/EP ᆯ테니/EC 심심풀이/NNG 로/JKB 한/MM 번/NNB 보__01/VV 시/EP 지요/EF ?/SF'},
{'name':'-으로 (-(u)lo)','sentence':'또 다른 입력장치로는 마우스와 스캐너 등이 있다.','pos_sentence':'또/MAG 다른/MM 입력/NNG 장치__07/NNG 로/JKB 는/JX 마우스__02/NNG 와/JC 스캐너/NNG 등__05/NNB 이/JKS 있/VV 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'펜싱 경기의 용어는 모두 프랑스어로 쓰이고 있다.','pos_sentence':'펜싱/NNG 경기__11/NNG 의/JKG 용어__02/NNG 는/JX 모두/MAG 프랑스어/NNP 로/JKB 쓰이__03/VV 고/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그것은 대통합의 신당으로 나타나야 한다.','pos_sentence':'그것/NP 은/JX 대/XPN 통합/NNG 의/JKG 신/XPN 당__14/NNG 으로/JKB 나타나/VV 아야/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그리고 과일은 양념으로 먹는 정도여야 한다.','pos_sentence':'그리고/MAJ 과일__01/NNG 은/JX 양념/NNG 으로/JKB 먹__02/VV 는/ETM 정도__11/NNG 이/VCP 어야/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'옛어른은 사람은 열십자로 생각하라고 하였다.','pos_sentence':'옛/MM 어른/NNG 은/JX 사람/NNG 은/JX 열십자/NNG 로/JKB 생각__01/NNG 하/XSV 라고/EC 하/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'관현악이나 실내악 등 주로 합주용으로 쓰인다.','pos_sentence':'관현악/NNG 이나/JC 실내악__02/NNG 등__05/NNB 주로/MAG 합주__01/NNG 용/XSN 으로/JKB 쓰이__03/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'옛날에는 꽃을 말려 약으로 사용했다.','pos_sentence':'옛날/NNG 에/JKB 는/JX 꽃__01/NNG 을/JKO 말리__03/VV 어/EC 약__07/NNG 으로/JKB 사용__04/NNG 하/XSV 았/EP 다/EF ./SF'}]}
,{'postposition':'lo','function':'ins','sentences':[{'name':'-으로 (-(u)lo)','sentence':'그때 두 카메라맨이 인터컴으로 대화를 한다.','pos_sentence':'그때/NNG 두/MM 카메라맨/NNG 이/JKS 인터컴/NNG 으로/JKB 대화__06/NNG 를/JKO 하/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'틀바느질 재봉틀로 바느질선을 박는일.','pos_sentence':'틀바느질/NNG 재봉틀/NNG 로/JKB 바느질/NNG 선__14/NNG 을/JKO 박/VV 는/ETM 일__01/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'엄마는 기어코 옷고름으로 눈물을 찍어 냈다.','pos_sentence':'엄마/NNG 는/JX 기어코/MAG 옷고름/NNG 으로/JKB 눈물__01/NNG 을/JKO 찍__02/VV 어/EC 내/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'거리는 연일 최루탄 연기로 뒤덮였다.','pos_sentence':'거리__01/NNG 는/JX 연일__01/NNG 최루탄/NNG 연기__09/NNG 로/JKB 뒤덮이/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'한 목사는 교회 장비로 직접 방송도 했다.','pos_sentence':'한/NNP 목사__05/NNG 는/JX 교회__02/NNG 장비__07/NNG 로/JKB 직접/MAG 방송__01/NNG 도/JX 하/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'공업용 재봉틀 한 대로 가게문을 연 정우성씨.','pos_sentence':'공업__01/NNG 용/XSN 재봉틀/NNG 한/MM 대__15/NNB 로/JKB 가게/NNG 문__05/NNG 을/JKO 열__02/VV ᆫ/ETM 정우성/NNP 씨/NNB ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'부겐빌레아 그늘, 흙으로 덮은 자리는 그대로였다.','pos_sentence':'부겐빌레아/NNG 그늘/NNG ,/SP 흙/NNG 으로/JKB 덮/VV 은/ETM 자리__01/NNG 는/JX 그대로/MAG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'장모가 수건으로 얼굴을 감싸면서 오열했다.','pos_sentence':'장모__01/NNG 가/JKS 수건/NNG 으로/JKB 얼굴/NNG 을/JKO 감싸/VV 면서/EC 오열__08/NNG 하/XSV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'뒷산은 어느새 연초록 새 잎으로 덮여 있었다.','pos_sentence':'뒷산/NNG 은/JX 어느새/MAG 연초록/NNG 새/MM 잎/NNG 으로/JKB 덮이/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'드라이버로 나사를 풀어 팬을 해체한다.','pos_sentence':'드라이버/NNG 로/JKB 나사__01/NNG 를/JKO 풀/VV 어/EC 팬__02/NNG 을/JKO 해체__03/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'효철은 수건으로 땀을 닦고 있었다.','pos_sentence':'효철/NNP 은/JX 수건/NNG 으로/JKB 땀__01/NNG 을/JKO 닦__01/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'적을 공격할 때는 적의 칼로 쳐라.','pos_sentence':'적__13/NNG 을/JKO 공격__02/NNG 하/XSV ᆯ/ETM 때__01/NNG 는/JX 적__13/NNG 의/JKG 칼__01/NNG 로/JKB 치__02/VV 어라/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그리고 그 핏줄기를 채찍으로 거머쥐고 싶어한다.','pos_sentence':'그리고/MAJ 그/MM 핏줄기/NNG 를/JKO 채찍/NNG 으로/JKB 거머쥐/VV 고/EC 싶/VX 어/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'지우개로 빡빡 지워버리고 싶은 헤드라인이었다.','pos_sentence':'지우개/NNG 로/JKB 빡빡__01/MAG 지우__01/VV 어/EC 버리/VX 고/EC 싶/VX 은/ETM 헤드라인/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아이라이너로 촘촘히 채우도록 한다.','pos_sentence':'아이라이너/NNG 로/JKB 촘촘히/MAG 채우__03/VV 도록/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그곳의 여성은 아예 천으로 온몸을 덮어버립니다.','pos_sentence':'그곳/NP 의/JKG 여성__01/NNG 은/JX 아예/MAG 천__01/NNG 으로/JKB 온몸/NNG 을/JKO 덮/VV 어/EC 버리/VX ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그런데 그 안경으로 나는 또 한 가지를 보았습니다.','pos_sentence':'그런데/MAJ 그/MM 안경__03/NNG 으로/JKB 나/NP 는/JX 또/MAG 한/MM 가지/NNB 를/JKO 보__01/VV 았/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'변기로 받아 내야 한다.','pos_sentence':'변기__01/NNG 로/JKB 받__01/VV 아/EC 내/VX 어야/EC 하/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'나는 창으로 병원 안을 들여다보았다.','pos_sentence':'나/NP 는/JX 창__09/NNG 으로/JKB 병원__02/NNG 안__01/NNG 을/JKO 들여다보/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'방적 방적사 섬유로 실을 뽑아 내는 일.','pos_sentence':'방적__02/NNG 방적사/NNG 섬유/NNG 로/JKB 실__01/NNG 을/JKO 뽑/VV 아/EC 내/VX 는/ETM 일__01/NNG ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'무 당근처럼 수세미로 표면의 흙을 닦는다.','pos_sentence':'무__02/NNG 당근/NNG 처럼/JKB 수세미__01/NNG 로/JKB 표면/NNG 의/JKG 흙/NNG 을/JKO 닦__01/VV 는다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'몽둥이로 세간도 박살을 냈다.','pos_sentence':'몽둥이/NNG 로/JKB 세간__01/NNG 도/JX 박살__01/NNG 을/JKO 내__02/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'사내는 다시 손수건으로 안경 밑을 눌렀다.','pos_sentence':'사내__01/NNG 는/JX 다시/MAG 손수건/NNG 으로/JKB 안경__03/NNG 밑__01/NNG 을/JKO 누르/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그리고 입과 눈은 테이프로 막혀 있었다.','pos_sentence':'그리고/MAJ 입/NNG 과/JC 눈__01/NNG 은/JX 테이프/NNG 로/JKB 막히/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'은실 거미줄로 방벽을 이룬 구멍을 조사한다.','pos_sentence':'은__04/NNG 실__01/NNG 거미줄/NNG 로/JKB 방벽/NNG 을/JKO 이루__01/VV ᆫ/ETM 구멍/NNG 을/JKO 조사__30/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'털실로 짠 조끼였다.','pos_sentence':'털실/NNG 로/JKB 짜__01/VV ᆫ/ETM 조끼__01/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'경지 핸드폰으로 전화를 걸어볼까?','pos_sentence':'경지/NNP 핸드폰/NNG 으로/JKB 전화__07/NNG 를/JKO 걸__02/VV 어/EC 보/VX ᆯ까/EF ?/SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 위를 지우개로 문질러 보자.','pos_sentence':'그/MM 위__01/NNG 를/JKO 지우개/NNG 로/JKB 문지르/VV 어/EC 보/VX 자/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'기계로 뽑는 게 아니다.','pos_sentence':'기계__07/NNG 로/JKB 뽑/VV 는/ETM 것/NNB 이/JKC 아니/VCN 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'진주로 다이얼을 돌렸다.','pos_sentence':'진주/NNP 로/JKB 다이얼/NNG 을/JKO 돌리__04/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'카메라로 세상을 다시 봐.','pos_sentence':'카메라/NNG 로/JKB 세상__01/NNG 을/JKO 다시/MAG 보__01/VV 아/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'지구가 아스팔트로 뒤덮여 있는 것만은 아니다.','pos_sentence':'지구__04/NNG 가/JKS 아스팔트/NNG 로/JKB 뒤덮이/VV 어/EC 있/VX 는/ETM 것/NNB 만/JX 은/JX 아니/VCN 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'몰딩 부분을 칼로 도려내어 깔끔하게 정리한다.','pos_sentence':'몰딩/NNG 부분__01/NNG 을/JKO 칼__01/NNG 로/JKB 도려내/VV 어/EC 깔끔/XR 하/XSA 게/EC 정리__09/NNG 하/XSV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'남편이 책꽂이 뒤를 우산끝으로 쿡쿡 눌렀다.','pos_sentence':'남편__01/NNG 이/JKS 책꽂이/NNG 뒤__01/NNG 를/JKO 우산__01/NNG 끝/NNG 으로/JKB 쿡쿡/MAG 누르/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'볍씨 가마니를 솔가지로 덮어 둔다.','pos_sentence':'볍씨/NNG 가마니/NNG 를/JKO 솔가지/NNG 로/JKB 덮/VV 어/EC 두/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'필터는 물로 씻어 준다.','pos_sentence':'필터/NNG 는/JX 물__01/NNG 로/JKB 씻/VV 어/EC 주/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'마을회관 옆쪽의 시멘트로 포장된 소로를 따라간다.','pos_sentence':'마을__01/NNG 회관/NNG 옆쪽/NNG 의/JKG 시멘트/NNG 로/JKB 포장__10/NNG 되/XSV ᆫ/ETM 소로__01/NNG 를/JKO 따라가/VV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'교무실에서 고지서를 라이타로 불태워버렸었다.','pos_sentence':'교무실/NNG 에서/JKB 고지서/NNG 를/JKO 라이타/NNG 로/JKB 불태우/VV 어/EC 버리/VX 었었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'바로 이 펜으로 이 글을 쓰고 있다.','pos_sentence':'바로/MAG 이__05/MM 펜/NNG 으로/JKB 이__05/MM 글/NNG 을/JKO 쓰__01/VV 고/EC 있/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'밥은 새옹이라는 놋쇠솥으로 녹음메를 짓는다.','pos_sentence':'밥__01/NNG 은/JX 새옹/NNG 이/VCP 라는/ETM 놋쇠/NNG 솥/NNG 으로/JKB 녹음메/NNG 를/JKO 짓__01/VV 는다/EF ./SF'}]}
,{'postposition':'lo','function':'loc','sentences':[{'name':'-으로 (-(u)lo)','sentence':'산들산들 가지 사이로 바람이 지나갔습니다.','pos_sentence':'산들산들/MAG 가지__01/NNG 사이__01/NNG 로/JKB 바람__01/NNG 이/JKS 지나가/VV 았/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'석양이 정면으로 촌부의 눈앞을 가로막았다.','pos_sentence':'석양__01/NNG 이/JKS 정면__01/NNG 으로/JKB 촌부__03/NNG 의/JKG 눈앞/NNG 을/JKO 가로막/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'쇠창 밖으로 눈이 펑펑 내리고 있었다.','pos_sentence':'쇠창/NNG 밖/NNG 으로/JKB 눈__04/NNG 이/JKS 펑펑__03/MAG 내리/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'붉은색 복도 카펫 위로 물이 괴어 있었다.','pos_sentence':'붉은색/NNG 복도__04/NNG 카펫/NNG 위__01/NNG 로/JKB 물__01/NNG 이/JKS 괴__01/VV 어/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'철장 사이로 쳐다봐야 하는 형제들의 아픔!','pos_sentence':'철장__04/NNG 사이__01/NNG 로/JKB 쳐다보/VV 아야/EC 하/VX 는/ETM 형제__01/NNG 들/XSN 의/JKG 아픔/NNG !/SF'},
{'name':'-으로 (-(u)lo)','sentence':'우리 모두 경기도 화성군 남양면 활초리 홍난파 앞으로 편지를 보내자.','pos_sentence':'우리/NP 모두/MAG 경기도/NNP 화성군/NNP 남양면/NNP 활초리/NNP 홍난파/NNP 앞/NNG 으로/JKB 편지__02/NNG 를/JKO 보내/VV 자/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'나는 가로수 뒤로 몸을 숨겼다.','pos_sentence':'나/NP 는/JX 가로수/NNG 뒤__01/NNG 로/JKB 몸__01/NNG 을/JKO 숨기/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 사이로 둘은 마치 도둑고양이들처럼 나아갔습니다.','pos_sentence':'그/MM 사이__01/NNG 로/JKB 둘/NR 은/JX 마치/MAG 도둑고양이/NNG 들/XSN 처럼/JKB 나아가/VV 았/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'시멘트 담벼락 너머로 마루며 집안이 들여다보였다.','pos_sentence':'시멘트/NNG 담벼락/NNG 너머/NNG 로/JKB 마루__03/NNG 이/VCP 며/EC 집안__01/NNG 이/JKS 들여다보이/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'205번과 206번 나무 사이로 사리탑이 보였다.','pos_sentence':'205/SN 번/NNB 과/JKB 206/SN 번/NNB 나무__01/NNG 사이__01/NNG 로/JKB 사리탑/NNG 이/JKS 보이__01/VV 었/EP 다/EF ./SF'},{'name':'-으로 (-(u)lo)','sentence':'담 너머로 정수리까지 보았어.','pos_sentence':'담__01/NNG 너머/NNG 로/JKB 정수리/NNG 까지/JX 보__01/VV 았/EP 어/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 한쪽 가장자리로 돼지우리와 닭장이 있었다.','pos_sentence':'그/MM 한쪽/NNG 가장자리/NNG 로/JKB 돼지우리/NNG 와/JC 닭장/NNG 이/JKS 있/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'엘리베이터 문짝의 무늬 사이로 자신의 모습이 비쳤다.','pos_sentence':'엘리베이터/NNG 문짝/NNG 의/JKG 무늬/NNG 사이__01/NNG 로/JKB 자신__01/NNG 의/JKG 모습__01/NNG 이/JKS 비치__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그는 축대 너머로 무엇인가를 보았다.','pos_sentence':'그/NP 는/JX 축대/NNG 너머/NNG 로/JKB 무엇/NP 이/VCP ᆫ가/EC 를/JKO 보__01/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'전교생이 운동장으로 모이라는 종소리였습니다.','pos_sentence':'전교__01/NNG 생/XSN 이/JKS 운동장/NNG 으로/JKB 모이/VV 라는/ETM 종소리/NNG 이/VCP 었/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'차창 밖으로 어촌 풍경이 보였다.','pos_sentence':'차창/NNG 밖/NNG 으로/JKB 어촌/NNG 풍경__01/NNG 이/JKS 보이__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'유리창 너머로 모 국회의원의 얼굴이 보였다.','pos_sentence':'유리창/NNG 너머/NNG 로/JKB 모__15/MM 국회의원/NNG 의/JKG 얼굴/NNG 이/JKS 보이__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'나는 창 밖으로 논둑을 내다보았다.','pos_sentence':'나/NP 는/JX 창__09/NNG 밖/NNG 으로/JKB 논둑/NNG 을/JKO 내다보/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'차창 밖으로 바다가 보였어.','pos_sentence':'차창/NNG 밖/NNG 으로/JKB 바다/NNG 가/JKS 보이__01/VV 었/EP 어/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아이들까지 종갓집으로 몰려간 모양이다.','pos_sentence':'아이__01/NNG 들/XSN 까지/JX 종갓집/NNG 으로/JKB 몰려가/VV ᆫ/ETM 모양__02/NNG 이/VCP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그래도 단골 손님이 많은 곳으로 유명하다.','pos_sentence':'그래도/MAJ 단골__01/NNG 손__02/NNG 님/XSN 이/JKS 많/VA 은/ETM 곳__01/NNG 으로/JKB 유명/XR 하/XSA 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'저만큼 잔솔밭 사이로 원피스 자락이 보였다.','pos_sentence':'저만큼/MAG 잔솔밭/NNG 사이__01/NNG 로/JKB 원피스/NNG 자락__01/NNG 이/JKS 보이__01/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'구름 사이로 빛나는 초생대 지형들.','pos_sentence':'구름__01/NNG 사이__01/NNG 로/JKB 빛나/VV 는/ETM 초생대/NNG 지형/NNG 들/XSN ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 사이로 히딩크 감독과 선수들의 모습이 보입니다.','pos_sentence':'그/MM 사이__01/NNG 로/JKB 히딩크/NNP 감독__02/NNG 과/JC 선수__05/NNG 들/XSN 의/JKG 모습__01/NNG 이/JKS 보이__01/VV ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'우린 옆 골목 여관으로 자리를 잡았다.','pos_sentence':'우리/NP ᆫ/JX 옆/NNG 골목__01/NNG 여관__03/NNG 으로/JKB 자리__01/NNG 를/JKO 잡__01/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그녀의 어깨 너머로 제단이 눈에 들어왔다.','pos_sentence':'그녀/NP 의/JKG 어깨__01/NNG 너머/NNG 로/JKB 제단__02/NNG 이/JKS 눈__01/NNG 에/JKB 들어오/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'효철은 다희의 머리칼 사이로 얼굴을 묻었다.','pos_sentence':'효철/NNP 은/JX 다희/NNP 의/JKG 머리칼/NNG 사이__01/NNG 로/JKB 얼굴/NNG 을/JKO 묻__02/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'영애는 커텐 사이로 들여다보았다.','pos_sentence':'영애/NNP 는/JX 커텐/NNG 사이__01/NNG 로/JKB 들여다보/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'신문사가 효창공원 옆으로 이사를 한 것이다.','pos_sentence':'신문사/NNG 가/JKS 효창공원/NNP 옆/NNG 으로/JKB 이사__14/NNG 를/JKO 하/VV ᆫ/ETM 것/NNB 이/VCP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'그 입 사이로 금니가 살짝 보입니다.','pos_sentence':'그/MM 입/NNG 사이__01/NNG 로/JKB 금니__01/NNG 가/JKS 살짝/MAG 보이__01/VV ᄇ니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'햇빛은 아카시아 나무 사이로 은빛 비늘처럼 퍼덕였다.','pos_sentence':'햇빛/NNG 은/JX 아카시아/NNG 나무__01/NNG 사이__01/NNG 로/JKB 은빛/NNG 비늘__01/NNG 처럼/JKB 퍼덕이/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'여건만 주어진다면 연해주로 이주하고 싶다.','pos_sentence':'여건__01/NNG 만/JX 주어지/VV ᆫ다면/EC 연해주/NNP 로/JKB 이주__06/NNG 하/XSV 고/EC 싶/VX 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'저는 블라인드 사이로 밖을 내다보았습니다.','pos_sentence':'저/NP 는/JX 블라인드/NNG 사이__01/NNG 로/JKB 밖/NNG 을/JKO 내다보/VV 았/EP 습니다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'경품은 원하는 주소로 배달해 준다.','pos_sentence':'경품/NNG 은/JX 원하__02/VV 는/ETM 주소__01/NNG 로/JKB 배달/NNG 하/XSV 아/EC 주/VX ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'단원의 고향은 확증이 없으나 안산으로 추정된다.','pos_sentence':'단원/NNP 의/JKG 고향__02/NNG 은/JX 확증/NNG 이/JKS 없/VA 으나/EC 안산/NNP 으로/JKB 추정__02/NNG 되/XSV ᆫ다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'춘기는 유리창 너머로 경찰서 정문을 살폈다.','pos_sentence':'춘기/NNP 는/JX 유리창/NNG 너머/NNG 로/JKB 경찰서/NNG 정문__03/NNG 을/JKO 살피/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'아이들은 울타리 사이로 염소에게 종이를 주었다.','pos_sentence':'아이__01/NNG 들/XSN 은/JX 울타리/NNG 사이__01/NNG 로/JKB 염소__01/NNG 에게/JKB 종이__01/NNG 를/JKO 주/VV 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'남조는 가만히 문틈으로 방 안을 들여다봤다.','pos_sentence':'남조/NNP 는/JX 가만히/MAG 문틈/NNG 으로/JKB 방__07/NNG 안__01/NNG 을/JKO 들여다보/VV 았/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'담장너머로 그의 집을 쳐다보고 있었다.','pos_sentence':'담장__01/NNG 너머/NNG 로/JKB 그/NP 의/JKG 집__01/NNG 을/JKO 쳐다보/VV 고/EC 있/VX 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'격자창 너머로 데크와 처마가 보이는 거실이었다.','pos_sentence':'격자창/NNG 너머/NNG 로/JKB 데크/NNG 와/JC 처마__01/NNG 가/JKS 보이__01/VV 는/ETM 거실__02/NNG 이/VCP 었/EP 다/EF ./SF'},
{'name':'-으로 (-(u)lo)','sentence':'양편으로 사람들이 주욱 서 있었다.','pos_sentence':'양/MM 편__04/NNB 으로/JKB 사람/NNG 들/XSN 이/JKS 주욱/MAG 서/VV 어/EC 있/VX 었/EP 다/EF ./SF'}]}]
